<?php
/**
 * BrazilCpfProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * BrazilCpfProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for the &#x60;brazil-cpf-lookup&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BrazilCpfProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'BrazilCpfProviderOutput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'preview_raw_error_code' => 'string',
        'cpf_number' => 'string',
        'fiscal_regions' => 'string[]',
        'status_code' => 'int',
        'status_description' => 'string',
        'name' => 'string',
        'social_name' => 'string',
        'date_of_birth' => '\DateTime',
        'year_of_death' => 'string',
        'date_of_registration' => '\DateTime',
        'biometric_verification' => '\Trinsic\Api\Model\BrazilBiometricVerificationOutput'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'preview_raw_error_code' => null,
        'cpf_number' => null,
        'fiscal_regions' => null,
        'status_code' => 'int32',
        'status_description' => null,
        'name' => null,
        'social_name' => null,
        'date_of_birth' => 'date',
        'year_of_death' => null,
        'date_of_registration' => 'date',
        'biometric_verification' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'preview_raw_error_code' => true,
        'cpf_number' => true,
        'fiscal_regions' => true,
        'status_code' => true,
        'status_description' => true,
        'name' => true,
        'social_name' => true,
        'date_of_birth' => true,
        'year_of_death' => true,
        'date_of_registration' => true,
        'biometric_verification' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'preview_raw_error_code' => 'preview_raw_error_code',
        'cpf_number' => 'cpfNumber',
        'fiscal_regions' => 'fiscalRegions',
        'status_code' => 'statusCode',
        'status_description' => 'statusDescription',
        'name' => 'name',
        'social_name' => 'socialName',
        'date_of_birth' => 'dateOfBirth',
        'year_of_death' => 'yearOfDeath',
        'date_of_registration' => 'dateOfRegistration',
        'biometric_verification' => 'biometricVerification'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'preview_raw_error_code' => 'setPreviewRawErrorCode',
        'cpf_number' => 'setCpfNumber',
        'fiscal_regions' => 'setFiscalRegions',
        'status_code' => 'setStatusCode',
        'status_description' => 'setStatusDescription',
        'name' => 'setName',
        'social_name' => 'setSocialName',
        'date_of_birth' => 'setDateOfBirth',
        'year_of_death' => 'setYearOfDeath',
        'date_of_registration' => 'setDateOfRegistration',
        'biometric_verification' => 'setBiometricVerification'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'preview_raw_error_code' => 'getPreviewRawErrorCode',
        'cpf_number' => 'getCpfNumber',
        'fiscal_regions' => 'getFiscalRegions',
        'status_code' => 'getStatusCode',
        'status_description' => 'getStatusDescription',
        'name' => 'getName',
        'social_name' => 'getSocialName',
        'date_of_birth' => 'getDateOfBirth',
        'year_of_death' => 'getYearOfDeath',
        'date_of_registration' => 'getDateOfRegistration',
        'biometric_verification' => 'getBiometricVerification'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('preview_raw_error_code', $data ?? [], null);
        $this->setIfExists('cpf_number', $data ?? [], null);
        $this->setIfExists('fiscal_regions', $data ?? [], null);
        $this->setIfExists('status_code', $data ?? [], null);
        $this->setIfExists('status_description', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('social_name', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('year_of_death', $data ?? [], null);
        $this->setIfExists('date_of_registration', $data ?? [], null);
        $this->setIfExists('biometric_verification', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets preview_raw_error_code
     *
     * @return string|null
     */
    public function getPreviewRawErrorCode()
    {
        return $this->container['preview_raw_error_code'];
    }

    /**
     * Sets preview_raw_error_code
     *
     * @param string|null $preview_raw_error_code The raw error code for the verification, returned by Serpro.              This is a temporary preview to support detailed error handling. When building against this please let the Trinsic team know. Preview features can be turned off without an obsoletion notice.
     *
     * @return self
     */
    public function setPreviewRawErrorCode($preview_raw_error_code)
    {
        if (is_null($preview_raw_error_code)) {
            array_push($this->openAPINullablesSetToNull, 'preview_raw_error_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('preview_raw_error_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['preview_raw_error_code'] = $preview_raw_error_code;

        return $this;
    }

    /**
     * Gets cpf_number
     *
     * @return string|null
     */
    public function getCpfNumber()
    {
        return $this->container['cpf_number'];
    }

    /**
     * Sets cpf_number
     *
     * @param string|null $cpf_number The individual's CPF number.              A CPF (Cadastro de Pessoas Físicas) is the Brazilian individual taxpayer identification number for residents and foreigners. It is an 11-digit number managed by the Federal Revenue Service, the last 2 digits are check digits, calculated based on the first 9 digits. The 9th digit indicates the fiscal region responsible for the registration,
     *
     * @return self
     */
    public function setCpfNumber($cpf_number)
    {
        if (is_null($cpf_number)) {
            array_push($this->openAPINullablesSetToNull, 'cpf_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('cpf_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['cpf_number'] = $cpf_number;

        return $this;
    }

    /**
     * Gets fiscal_regions
     *
     * @return string[]|null
     */
    public function getFiscalRegions()
    {
        return $this->container['fiscal_regions'];
    }

    /**
     * Sets fiscal_regions
     *
     * @param string[]|null $fiscal_regions List of Brazilian fiscal regions that could have issued this number.              This is calculated based off of the CPF number. A CPF number encodes information about what region it is issued from, but some regions share the identifier.              Possible values: Formatted as two characters. The digit represents the region code this applies to. - AC (Acre) - 2 - AL (Alagoas) - 4 - AP (Amapá) - 2 - AM (Amazonas) - 2 - BA (Bahia) - 5 - CE (Ceará) - 3 - DF (Distrito Federal) - 1 - ES (Espírito Santo) - 7 - GO (Goiás) - 1 - MA (Maranhão) - 3 - MT (Mato Grosso) - 1 - MS (Mato Grosso do Sul) - 1 - MG (Minas Gerais) - 6 - PA (Pará) - 2 - PB (Paraíba) - 4 - PR (Paraná) - 9 - PE (Pernambuco) - 4 - PI (Piauí) - 3 - RJ (Rio de Janeiro) - 7 - RN (Rio Grande do Norte) - 4 - RO (Rondônia) - 2 - RS (Rio Grande do Sul) - 0 - RR (Roraima) - 2 - SC (Santa Catarina) - 9 - SP (São Paulo) - 8 - SE (Sergipe) - 5 - TO (Tocantins) - 1
     *
     * @return self
     */
    public function setFiscalRegions($fiscal_regions)
    {
        if (is_null($fiscal_regions)) {
            array_push($this->openAPINullablesSetToNull, 'fiscal_regions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fiscal_regions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fiscal_regions'] = $fiscal_regions;

        return $this;
    }

    /**
     * Gets status_code
     *
     * @return int|null
     */
    public function getStatusCode()
    {
        return $this->container['status_code'];
    }

    /**
     * Sets status_code
     *
     * @param int|null $status_code The CPF Status. Possible values: 0 - Regular. The CPF is valid and in good standing. There are no pending issues, registration inconsistencies, or missing mandatory Individual Income Tax Returns (DIRPF). 2 - Suspended. The CPF record contains incorrect or incomplete registration data (e.g., name, date of birth, or voter registration number). This status is typically caused by discrepancies with the Superior Electoral Court (TSE) database or failure to update personal information. 3 - Deceased Holder. The CPF has been registered as belonging to a deceased individual. This status is recorded to prevent post-mortem misuse. 4 - Pending Regularization. The taxpayer has failed to submit one or more mandatory Individual Income Tax Returns (DIRPF) within the last five years. This can occur for various reasons, such as failure to file a mandatory declaration, changes of address, name, marital status, or other important information that does not conform to the records. Regularization requires submission of the overdue returns. 5 - Canceled by Multiplicity. The CPF has been cancelled due to duplicate registration (multiple CPFs assigned to the same individual or a single CPF linked to multiple individuals). 8 - Null. The CPF registration was cancelled due to confirmed fraud or a serious issuance error. Regularization requires in-person verification at a Federal Revenue Service office and may not be guaranteed. 9 - Cancelled Ex Officio. The CPF was cancelled due to administrative or judicial decision, or other registration inconsistencies.
     *
     * @return self
     */
    public function setStatusCode($status_code)
    {
        if (is_null($status_code)) {
            array_push($this->openAPINullablesSetToNull, 'status_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status_code'] = $status_code;

        return $this;
    }

    /**
     * Gets status_description
     *
     * @return string|null
     */
    public function getStatusDescription()
    {
        return $this->container['status_description'];
    }

    /**
     * Sets status_description
     *
     * @param string|null $status_description Description of the CPF Status.
     *
     * @return self
     */
    public function setStatusDescription($status_description)
    {
        if (is_null($status_description)) {
            array_push($this->openAPINullablesSetToNull, 'status_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status_description'] = $status_description;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The full legal name of the individual.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets social_name
     *
     * @return string|null
     */
    public function getSocialName()
    {
        return $this->container['social_name'];
    }

    /**
     * Sets social_name
     *
     * @param string|null $social_name The social name of the individual in case the individual would like to use a different name than their full legal name.
     *
     * @return self
     */
    public function setSocialName($social_name)
    {
        if (is_null($social_name)) {
            array_push($this->openAPINullablesSetToNull, 'social_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('social_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['social_name'] = $social_name;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return \DateTime|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param \DateTime|null $date_of_birth The date of birth of the individual.
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_birth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_birth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets year_of_death
     *
     * @return string|null
     * @deprecated
     */
    public function getYearOfDeath()
    {
        return $this->container['year_of_death'];
    }

    /**
     * Sets year_of_death
     *
     * @param string|null $year_of_death Deprecated as of September 1, 2026.              The year of death of the individual, if applicable.
     *
     * @return self
     * @deprecated
     */
    public function setYearOfDeath($year_of_death)
    {
        if (is_null($year_of_death)) {
            array_push($this->openAPINullablesSetToNull, 'year_of_death');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('year_of_death', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['year_of_death'] = $year_of_death;

        return $this;
    }

    /**
     * Gets date_of_registration
     *
     * @return \DateTime|null
     */
    public function getDateOfRegistration()
    {
        return $this->container['date_of_registration'];
    }

    /**
     * Sets date_of_registration
     *
     * @param \DateTime|null $date_of_registration The date of registration of the individual with the Federal Revenue Service.
     *
     * @return self
     */
    public function setDateOfRegistration($date_of_registration)
    {
        if (is_null($date_of_registration)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_registration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_registration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_registration'] = $date_of_registration;

        return $this;
    }

    /**
     * Gets biometric_verification
     *
     * @return \Trinsic\Api\Model\BrazilBiometricVerificationOutput|null
     */
    public function getBiometricVerification()
    {
        return $this->container['biometric_verification'];
    }

    /**
     * Sets biometric_verification
     *
     * @param \Trinsic\Api\Model\BrazilBiometricVerificationOutput|null $biometric_verification The biometric verification results.              This is an optional configurable check.
     *
     * @return self
     */
    public function setBiometricVerification($biometric_verification)
    {
        if (is_null($biometric_verification)) {
            array_push($this->openAPINullablesSetToNull, 'biometric_verification');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('biometric_verification', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['biometric_verification'] = $biometric_verification;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


