<?php
/**
 * ClearProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * ClearProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for the &#x60;clear&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ClearProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ClearProviderOutput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'authenticated' => 'bool',
        'authentication_methods' => 'string[]',
        'activated_authentication_methods' => 'string[]',
        'checks' => '\Trinsic\Api\Model\ClearProviderOutputCheck[]',
        'check_metadata' => 'string[]',
        'completed_at' => '\DateTime',
        'created_at' => '\DateTime',
        'email' => 'string',
        'expires_at' => '\DateTime',
        'fields_to_collect' => 'string[]',
        'ip' => 'string[]',
        'phone' => 'string',
        'status' => 'string',
        'updated_at' => '\DateTime',
        'user_agent' => 'string[]',
        'user_created' => 'bool',
        'user_id' => 'string',
        'traits' => '\Trinsic\Api\Model\ClearProviderOutputTraits',
        'idv_status' => 'string',
        'sessions' => '\Trinsic\Api\Model\ClearProviderOutputSessionInfo[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'authenticated' => null,
        'authentication_methods' => null,
        'activated_authentication_methods' => null,
        'checks' => null,
        'check_metadata' => null,
        'completed_at' => 'date-time',
        'created_at' => 'date-time',
        'email' => null,
        'expires_at' => 'date-time',
        'fields_to_collect' => null,
        'ip' => null,
        'phone' => null,
        'status' => null,
        'updated_at' => 'date-time',
        'user_agent' => null,
        'user_created' => null,
        'user_id' => null,
        'traits' => null,
        'idv_status' => null,
        'sessions' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'authenticated' => true,
        'authentication_methods' => true,
        'activated_authentication_methods' => true,
        'checks' => true,
        'check_metadata' => true,
        'completed_at' => true,
        'created_at' => true,
        'email' => true,
        'expires_at' => true,
        'fields_to_collect' => true,
        'ip' => true,
        'phone' => true,
        'status' => true,
        'updated_at' => true,
        'user_agent' => true,
        'user_created' => true,
        'user_id' => true,
        'traits' => true,
        'idv_status' => true,
        'sessions' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'authenticated' => 'authenticated',
        'authentication_methods' => 'authenticationMethods',
        'activated_authentication_methods' => 'activatedAuthenticationMethods',
        'checks' => 'checks',
        'check_metadata' => 'checkMetadata',
        'completed_at' => 'completedAt',
        'created_at' => 'createdAt',
        'email' => 'email',
        'expires_at' => 'expiresAt',
        'fields_to_collect' => 'fieldsToCollect',
        'ip' => 'ip',
        'phone' => 'phone',
        'status' => 'status',
        'updated_at' => 'updatedAt',
        'user_agent' => 'userAgent',
        'user_created' => 'userCreated',
        'user_id' => 'userId',
        'traits' => 'traits',
        'idv_status' => 'idvStatus',
        'sessions' => 'sessions'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'authenticated' => 'setAuthenticated',
        'authentication_methods' => 'setAuthenticationMethods',
        'activated_authentication_methods' => 'setActivatedAuthenticationMethods',
        'checks' => 'setChecks',
        'check_metadata' => 'setCheckMetadata',
        'completed_at' => 'setCompletedAt',
        'created_at' => 'setCreatedAt',
        'email' => 'setEmail',
        'expires_at' => 'setExpiresAt',
        'fields_to_collect' => 'setFieldsToCollect',
        'ip' => 'setIp',
        'phone' => 'setPhone',
        'status' => 'setStatus',
        'updated_at' => 'setUpdatedAt',
        'user_agent' => 'setUserAgent',
        'user_created' => 'setUserCreated',
        'user_id' => 'setUserId',
        'traits' => 'setTraits',
        'idv_status' => 'setIdvStatus',
        'sessions' => 'setSessions'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'authenticated' => 'getAuthenticated',
        'authentication_methods' => 'getAuthenticationMethods',
        'activated_authentication_methods' => 'getActivatedAuthenticationMethods',
        'checks' => 'getChecks',
        'check_metadata' => 'getCheckMetadata',
        'completed_at' => 'getCompletedAt',
        'created_at' => 'getCreatedAt',
        'email' => 'getEmail',
        'expires_at' => 'getExpiresAt',
        'fields_to_collect' => 'getFieldsToCollect',
        'ip' => 'getIp',
        'phone' => 'getPhone',
        'status' => 'getStatus',
        'updated_at' => 'getUpdatedAt',
        'user_agent' => 'getUserAgent',
        'user_created' => 'getUserCreated',
        'user_id' => 'getUserId',
        'traits' => 'getTraits',
        'idv_status' => 'getIdvStatus',
        'sessions' => 'getSessions'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('authenticated', $data ?? [], null);
        $this->setIfExists('authentication_methods', $data ?? [], null);
        $this->setIfExists('activated_authentication_methods', $data ?? [], null);
        $this->setIfExists('checks', $data ?? [], null);
        $this->setIfExists('check_metadata', $data ?? [], null);
        $this->setIfExists('completed_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('fields_to_collect', $data ?? [], null);
        $this->setIfExists('ip', $data ?? [], null);
        $this->setIfExists('phone', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('user_agent', $data ?? [], null);
        $this->setIfExists('user_created', $data ?? [], null);
        $this->setIfExists('user_id', $data ?? [], null);
        $this->setIfExists('traits', $data ?? [], null);
        $this->setIfExists('idv_status', $data ?? [], null);
        $this->setIfExists('sessions', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets authenticated
     *
     * @return bool|null
     */
    public function getAuthenticated()
    {
        return $this->container['authenticated'];
    }

    /**
     * Sets authenticated
     *
     * @param bool|null $authenticated Whether CLEAR authenticated the individual.
     *
     * @return self
     */
    public function setAuthenticated($authenticated)
    {
        if (is_null($authenticated)) {
            array_push($this->openAPINullablesSetToNull, 'authenticated');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authenticated', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authenticated'] = $authenticated;

        return $this;
    }

    /**
     * Gets authentication_methods
     *
     * @return string[]|null
     */
    public function getAuthenticationMethods()
    {
        return $this->container['authentication_methods'];
    }

    /**
     * Sets authentication_methods
     *
     * @param string[]|null $authentication_methods The methods the individual authenticated with during the CLEAR flow.              Known values: - webauthn - email - sms_otp
     *
     * @return self
     */
    public function setAuthenticationMethods($authentication_methods)
    {
        if (is_null($authentication_methods)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_methods');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_methods', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['authentication_methods'] = $authentication_methods;

        return $this;
    }

    /**
     * Gets activated_authentication_methods
     *
     * @return string[]|null
     */
    public function getActivatedAuthenticationMethods()
    {
        return $this->container['activated_authentication_methods'];
    }

    /**
     * Sets activated_authentication_methods
     *
     * @param string[]|null $activated_authentication_methods The authentication methods the individual activated but did not use as a pre-existing credential during this session.              Known values: - webauthn - totp
     *
     * @return self
     */
    public function setActivatedAuthenticationMethods($activated_authentication_methods)
    {
        if (is_null($activated_authentication_methods)) {
            array_push($this->openAPINullablesSetToNull, 'activated_authentication_methods');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('activated_authentication_methods', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['activated_authentication_methods'] = $activated_authentication_methods;

        return $this;
    }

    /**
     * Gets checks
     *
     * @return \Trinsic\Api\Model\ClearProviderOutputCheck[]|null
     */
    public function getChecks()
    {
        return $this->container['checks'];
    }

    /**
     * Sets checks
     *
     * @param \Trinsic\Api\Model\ClearProviderOutputCheck[]|null $checks The checks CLEAR performed on the individual's data and each check's result.
     *
     * @return self
     */
    public function setChecks($checks)
    {
        if (is_null($checks)) {
            array_push($this->openAPINullablesSetToNull, 'checks');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('checks', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['checks'] = $checks;

        return $this;
    }

    /**
     * Gets check_metadata
     *
     * @return string[]|null
     */
    public function getCheckMetadata()
    {
        return $this->container['check_metadata'];
    }

    /**
     * Sets check_metadata
     *
     * @param string[]|null $check_metadata CLEAR error or metadata codes that influenced check results.
     *
     * @return self
     */
    public function setCheckMetadata($check_metadata)
    {
        if (is_null($check_metadata)) {
            array_push($this->openAPINullablesSetToNull, 'check_metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('check_metadata', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['check_metadata'] = $check_metadata;

        return $this;
    }

    /**
     * Gets completed_at
     *
     * @return \DateTime|null
     */
    public function getCompletedAt()
    {
        return $this->container['completed_at'];
    }

    /**
     * Sets completed_at
     *
     * @param \DateTime|null $completed_at The time the CLEAR verification session completed, as a UTC timestamp.
     *
     * @return self
     */
    public function setCompletedAt($completed_at)
    {
        if (is_null($completed_at)) {
            array_push($this->openAPINullablesSetToNull, 'completed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('completed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['completed_at'] = $completed_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at The time the CLEAR verification session was created, as a UTC timestamp.
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            array_push($this->openAPINullablesSetToNull, 'created_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email The individual's verified email address from the session.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at The time the CLEAR verification session expires, as a UTC timestamp.
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            array_push($this->openAPINullablesSetToNull, 'expires_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets fields_to_collect
     *
     * @return string[]|null
     */
    public function getFieldsToCollect()
    {
        return $this->container['fields_to_collect'];
    }

    /**
     * Sets fields_to_collect
     *
     * @param string[]|null $fields_to_collect The fields CLEAR still required to complete the current verification step.
     *
     * @return self
     */
    public function setFieldsToCollect($fields_to_collect)
    {
        if (is_null($fields_to_collect)) {
            array_push($this->openAPINullablesSetToNull, 'fields_to_collect');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('fields_to_collect', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['fields_to_collect'] = $fields_to_collect;

        return $this;
    }

    /**
     * Gets ip
     *
     * @return string[]|null
     */
    public function getIp()
    {
        return $this->container['ip'];
    }

    /**
     * Sets ip
     *
     * @param string[]|null $ip The IP addresses used to access this CLEAR verification session.
     *
     * @return self
     */
    public function setIp($ip)
    {
        if (is_null($ip)) {
            array_push($this->openAPINullablesSetToNull, 'ip');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ip', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ip'] = $ip;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string|null
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string|null $phone The individual's verified phone number, normalized to international E.164 format.
     *
     * @return self
     */
    public function setPhone($phone)
    {
        if (is_null($phone)) {
            array_push($this->openAPINullablesSetToNull, 'phone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The CLEAR verification session status.              Known values: - success - fail - awaiting_user_input - deferred - processing_data - expired - awaiting_manual_review - manual_success - manual_fail - canceled
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at The time the CLEAR verification session was most recently updated, as a UTC timestamp.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            array_push($this->openAPINullablesSetToNull, 'updated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updated_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets user_agent
     *
     * @return string[]|null
     */
    public function getUserAgent()
    {
        return $this->container['user_agent'];
    }

    /**
     * Sets user_agent
     *
     * @param string[]|null $user_agent The browser user agents that accessed this CLEAR verification session.
     *
     * @return self
     */
    public function setUserAgent($user_agent)
    {
        if (is_null($user_agent)) {
            array_push($this->openAPINullablesSetToNull, 'user_agent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_agent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_agent'] = $user_agent;

        return $this;
    }

    /**
     * Gets user_created
     *
     * @return bool|null
     */
    public function getUserCreated()
    {
        return $this->container['user_created'];
    }

    /**
     * Sets user_created
     *
     * @param bool|null $user_created Whether CLEAR created a new individual account during this session.
     *
     * @return self
     */
    public function setUserCreated($user_created)
    {
        if (is_null($user_created)) {
            array_push($this->openAPINullablesSetToNull, 'user_created');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_created', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_created'] = $user_created;

        return $this;
    }

    /**
     * Gets user_id
     *
     * @return string|null
     */
    public function getUserId()
    {
        return $this->container['user_id'];
    }

    /**
     * Sets user_id
     *
     * @param string|null $user_id The CLEAR identifier for the individual.
     *
     * @return self
     */
    public function setUserId($user_id)
    {
        if (is_null($user_id)) {
            array_push($this->openAPINullablesSetToNull, 'user_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['user_id'] = $user_id;

        return $this;
    }

    /**
     * Gets traits
     *
     * @return \Trinsic\Api\Model\ClearProviderOutputTraits|null
     */
    public function getTraits()
    {
        return $this->container['traits'];
    }

    /**
     * Sets traits
     *
     * @param \Trinsic\Api\Model\ClearProviderOutputTraits|null $traits The individual traits CLEAR returned after collecting enough information to make a decision.
     *
     * @return self
     */
    public function setTraits($traits)
    {
        if (is_null($traits)) {
            array_push($this->openAPINullablesSetToNull, 'traits');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('traits', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['traits'] = $traits;

        return $this;
    }

    /**
     * Gets idv_status
     *
     * @return string|null
     */
    public function getIdvStatus()
    {
        return $this->container['idv_status'];
    }

    /**
     * Sets idv_status
     *
     * @param string|null $idv_status The identity verification status.              Known documented value: - verified: CLEAR indicates the individual is verified.
     *
     * @return self
     */
    public function setIdvStatus($idv_status)
    {
        if (is_null($idv_status)) {
            array_push($this->openAPINullablesSetToNull, 'idv_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('idv_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['idv_status'] = $idv_status;

        return $this;
    }

    /**
     * Gets sessions
     *
     * @return \Trinsic\Api\Model\ClearProviderOutputSessionInfo[]|null
     */
    public function getSessions()
    {
        return $this->container['sessions'];
    }

    /**
     * Sets sessions
     *
     * @param \Trinsic\Api\Model\ClearProviderOutputSessionInfo[]|null $sessions Frontend session metadata CLEAR collected.
     *
     * @return self
     */
    public function setSessions($sessions)
    {
        if (is_null($sessions)) {
            array_push($this->openAPINullablesSetToNull, 'sessions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sessions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sessions'] = $sessions;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


