<?php
/**
 * CzechBankIdProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * CzechBankIdProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for the &#x60;czech-bank-id&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CzechBankIdProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'CzechBankIdProviderOutput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'subject_identifier' => 'string',
        'full_name' => 'string',
        'given_name' => 'string',
        'family_name' => 'string',
        'middle_name' => 'string',
        'nickname' => 'string',
        'preferred_username' => 'string',
        'gender' => 'string',
        'date_of_birth' => 'string',
        'birth_number' => 'string',
        'age' => 'int',
        'is_adult' => 'bool',
        'date_of_death' => '\DateTime',
        'birth_place' => 'string',
        'birth_country' => 'string',
        'primary_nationality' => 'string',
        'nationalities' => 'string[]',
        'marital_status' => 'string',
        'email' => 'string',
        'email_verified' => 'bool',
        'phone_number' => 'string',
        'phone_number_verified' => 'bool',
        'is_politically_exposed_person' => 'bool',
        'limited_legal_capacity' => 'bool',
        'verification' => '\Trinsic\Api\Model\CzechBankIdVerification',
        'addresses' => '\Trinsic\Api\Model\CzechBankIdAddress[]',
        'id_cards' => '\Trinsic\Api\Model\CzechBankIdCard[]',
        'updated_at' => '\DateTime',
        'zone_info' => 'string',
        'locale' => 'string',
        'titles' => '\Trinsic\Api\Model\CzechBankIdTitle[]'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'subject_identifier' => null,
        'full_name' => null,
        'given_name' => null,
        'family_name' => null,
        'middle_name' => null,
        'nickname' => null,
        'preferred_username' => null,
        'gender' => null,
        'date_of_birth' => null,
        'birth_number' => null,
        'age' => 'int32',
        'is_adult' => null,
        'date_of_death' => 'date',
        'birth_place' => null,
        'birth_country' => null,
        'primary_nationality' => null,
        'nationalities' => null,
        'marital_status' => null,
        'email' => null,
        'email_verified' => null,
        'phone_number' => null,
        'phone_number_verified' => null,
        'is_politically_exposed_person' => null,
        'limited_legal_capacity' => null,
        'verification' => null,
        'addresses' => null,
        'id_cards' => null,
        'updated_at' => 'date-time',
        'zone_info' => null,
        'locale' => null,
        'titles' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'subject_identifier' => true,
        'full_name' => true,
        'given_name' => true,
        'family_name' => true,
        'middle_name' => true,
        'nickname' => true,
        'preferred_username' => true,
        'gender' => true,
        'date_of_birth' => true,
        'birth_number' => true,
        'age' => true,
        'is_adult' => true,
        'date_of_death' => true,
        'birth_place' => true,
        'birth_country' => true,
        'primary_nationality' => true,
        'nationalities' => true,
        'marital_status' => true,
        'email' => true,
        'email_verified' => true,
        'phone_number' => true,
        'phone_number_verified' => true,
        'is_politically_exposed_person' => true,
        'limited_legal_capacity' => true,
        'verification' => true,
        'addresses' => true,
        'id_cards' => true,
        'updated_at' => true,
        'zone_info' => true,
        'locale' => true,
        'titles' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'subject_identifier' => 'subjectIdentifier',
        'full_name' => 'fullName',
        'given_name' => 'givenName',
        'family_name' => 'familyName',
        'middle_name' => 'middleName',
        'nickname' => 'nickname',
        'preferred_username' => 'preferredUsername',
        'gender' => 'gender',
        'date_of_birth' => 'dateOfBirth',
        'birth_number' => 'birthNumber',
        'age' => 'age',
        'is_adult' => 'isAdult',
        'date_of_death' => 'dateOfDeath',
        'birth_place' => 'birthPlace',
        'birth_country' => 'birthCountry',
        'primary_nationality' => 'primaryNationality',
        'nationalities' => 'nationalities',
        'marital_status' => 'maritalStatus',
        'email' => 'email',
        'email_verified' => 'emailVerified',
        'phone_number' => 'phoneNumber',
        'phone_number_verified' => 'phoneNumberVerified',
        'is_politically_exposed_person' => 'isPoliticallyExposedPerson',
        'limited_legal_capacity' => 'limitedLegalCapacity',
        'verification' => 'verification',
        'addresses' => 'addresses',
        'id_cards' => 'idCards',
        'updated_at' => 'updatedAt',
        'zone_info' => 'zoneInfo',
        'locale' => 'locale',
        'titles' => 'titles'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'subject_identifier' => 'setSubjectIdentifier',
        'full_name' => 'setFullName',
        'given_name' => 'setGivenName',
        'family_name' => 'setFamilyName',
        'middle_name' => 'setMiddleName',
        'nickname' => 'setNickname',
        'preferred_username' => 'setPreferredUsername',
        'gender' => 'setGender',
        'date_of_birth' => 'setDateOfBirth',
        'birth_number' => 'setBirthNumber',
        'age' => 'setAge',
        'is_adult' => 'setIsAdult',
        'date_of_death' => 'setDateOfDeath',
        'birth_place' => 'setBirthPlace',
        'birth_country' => 'setBirthCountry',
        'primary_nationality' => 'setPrimaryNationality',
        'nationalities' => 'setNationalities',
        'marital_status' => 'setMaritalStatus',
        'email' => 'setEmail',
        'email_verified' => 'setEmailVerified',
        'phone_number' => 'setPhoneNumber',
        'phone_number_verified' => 'setPhoneNumberVerified',
        'is_politically_exposed_person' => 'setIsPoliticallyExposedPerson',
        'limited_legal_capacity' => 'setLimitedLegalCapacity',
        'verification' => 'setVerification',
        'addresses' => 'setAddresses',
        'id_cards' => 'setIdCards',
        'updated_at' => 'setUpdatedAt',
        'zone_info' => 'setZoneInfo',
        'locale' => 'setLocale',
        'titles' => 'setTitles'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'subject_identifier' => 'getSubjectIdentifier',
        'full_name' => 'getFullName',
        'given_name' => 'getGivenName',
        'family_name' => 'getFamilyName',
        'middle_name' => 'getMiddleName',
        'nickname' => 'getNickname',
        'preferred_username' => 'getPreferredUsername',
        'gender' => 'getGender',
        'date_of_birth' => 'getDateOfBirth',
        'birth_number' => 'getBirthNumber',
        'age' => 'getAge',
        'is_adult' => 'getIsAdult',
        'date_of_death' => 'getDateOfDeath',
        'birth_place' => 'getBirthPlace',
        'birth_country' => 'getBirthCountry',
        'primary_nationality' => 'getPrimaryNationality',
        'nationalities' => 'getNationalities',
        'marital_status' => 'getMaritalStatus',
        'email' => 'getEmail',
        'email_verified' => 'getEmailVerified',
        'phone_number' => 'getPhoneNumber',
        'phone_number_verified' => 'getPhoneNumberVerified',
        'is_politically_exposed_person' => 'getIsPoliticallyExposedPerson',
        'limited_legal_capacity' => 'getLimitedLegalCapacity',
        'verification' => 'getVerification',
        'addresses' => 'getAddresses',
        'id_cards' => 'getIdCards',
        'updated_at' => 'getUpdatedAt',
        'zone_info' => 'getZoneInfo',
        'locale' => 'getLocale',
        'titles' => 'getTitles'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('subject_identifier', $data ?? [], null);
        $this->setIfExists('full_name', $data ?? [], null);
        $this->setIfExists('given_name', $data ?? [], null);
        $this->setIfExists('family_name', $data ?? [], null);
        $this->setIfExists('middle_name', $data ?? [], null);
        $this->setIfExists('nickname', $data ?? [], null);
        $this->setIfExists('preferred_username', $data ?? [], null);
        $this->setIfExists('gender', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('birth_number', $data ?? [], null);
        $this->setIfExists('age', $data ?? [], null);
        $this->setIfExists('is_adult', $data ?? [], null);
        $this->setIfExists('date_of_death', $data ?? [], null);
        $this->setIfExists('birth_place', $data ?? [], null);
        $this->setIfExists('birth_country', $data ?? [], null);
        $this->setIfExists('primary_nationality', $data ?? [], null);
        $this->setIfExists('nationalities', $data ?? [], null);
        $this->setIfExists('marital_status', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('email_verified', $data ?? [], null);
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('phone_number_verified', $data ?? [], null);
        $this->setIfExists('is_politically_exposed_person', $data ?? [], null);
        $this->setIfExists('limited_legal_capacity', $data ?? [], null);
        $this->setIfExists('verification', $data ?? [], null);
        $this->setIfExists('addresses', $data ?? [], null);
        $this->setIfExists('id_cards', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('zone_info', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('titles', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets subject_identifier
     *
     * @return string|null
     */
    public function getSubjectIdentifier()
    {
        return $this->container['subject_identifier'];
    }

    /**
     * Sets subject_identifier
     *
     * @param string|null $subject_identifier The subject identifier for the verified individual.
     *
     * @return self
     */
    public function setSubjectIdentifier($subject_identifier)
    {
        if (is_null($subject_identifier)) {
            array_push($this->openAPINullablesSetToNull, 'subject_identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subject_identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subject_identifier'] = $subject_identifier;

        return $this;
    }

    /**
     * Gets full_name
     *
     * @return string|null
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     *
     * @param string|null $full_name The individual's full name.
     *
     * @return self
     */
    public function setFullName($full_name)
    {
        if (is_null($full_name)) {
            array_push($this->openAPINullablesSetToNull, 'full_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('full_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets given_name
     *
     * @return string|null
     */
    public function getGivenName()
    {
        return $this->container['given_name'];
    }

    /**
     * Sets given_name
     *
     * @param string|null $given_name The individual's given or first name.
     *
     * @return self
     */
    public function setGivenName($given_name)
    {
        if (is_null($given_name)) {
            array_push($this->openAPINullablesSetToNull, 'given_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('given_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['given_name'] = $given_name;

        return $this;
    }

    /**
     * Gets family_name
     *
     * @return string|null
     */
    public function getFamilyName()
    {
        return $this->container['family_name'];
    }

    /**
     * Sets family_name
     *
     * @param string|null $family_name The individual's family or last name.
     *
     * @return self
     */
    public function setFamilyName($family_name)
    {
        if (is_null($family_name)) {
            array_push($this->openAPINullablesSetToNull, 'family_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('family_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['family_name'] = $family_name;

        return $this;
    }

    /**
     * Gets middle_name
     *
     * @return string|null
     */
    public function getMiddleName()
    {
        return $this->container['middle_name'];
    }

    /**
     * Sets middle_name
     *
     * @param string|null $middle_name The individual's middle name.
     *
     * @return self
     */
    public function setMiddleName($middle_name)
    {
        if (is_null($middle_name)) {
            array_push($this->openAPINullablesSetToNull, 'middle_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('middle_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['middle_name'] = $middle_name;

        return $this;
    }

    /**
     * Gets nickname
     *
     * @return string|null
     */
    public function getNickname()
    {
        return $this->container['nickname'];
    }

    /**
     * Sets nickname
     *
     * @param string|null $nickname Nickname used by a physical person              A casual name, not necessarily the legal given name.
     *
     * @return self
     */
    public function setNickname($nickname)
    {
        if (is_null($nickname)) {
            array_push($this->openAPINullablesSetToNull, 'nickname');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nickname', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nickname'] = $nickname;

        return $this;
    }

    /**
     * Gets preferred_username
     *
     * @return string|null
     */
    public function getPreferredUsername()
    {
        return $this->container['preferred_username'];
    }

    /**
     * Sets preferred_username
     *
     * @param string|null $preferred_username The individual's preferred username.              The user has chosen this as the preferred name for logins.
     *
     * @return self
     */
    public function setPreferredUsername($preferred_username)
    {
        if (is_null($preferred_username)) {
            array_push($this->openAPINullablesSetToNull, 'preferred_username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('preferred_username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['preferred_username'] = $preferred_username;

        return $this;
    }

    /**
     * Gets gender
     *
     * @return string|null
     */
    public function getGender()
    {
        return $this->container['gender'];
    }

    /**
     * Sets gender
     *
     * @param string|null $gender The individual's gender.              Possible values: - Male - Female - Other              Only returned for Identify verifications.
     *
     * @return self
     */
    public function setGender($gender)
    {
        if (is_null($gender)) {
            array_push($this->openAPINullablesSetToNull, 'gender');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('gender', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['gender'] = $gender;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return string|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param string|null $date_of_birth The individual's date of birth.              This is a string because the value may have reduced precision, such as only a year.
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_birth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_birth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets birth_number
     *
     * @return string|null
     */
    public function getBirthNumber()
    {
        return $this->container['birth_number'];
    }

    /**
     * Sets birth_number
     *
     * @param string|null $birth_number The individual's Czech birth number.              This value is written without the traditional forward slash. Czech birth numbers are Czech public-authority identifiers administered through the Ministry of Interior's birth-number register. The Ministry can assign one to Czech citizens and to foreign nationals with temporary or permanent residence in the Czech Republic. For foreign nationals, this is still a Czech birth number in the Czech format, not an identity number from another country.              The common current format is YYXXDDSSSC: - YY: Two digit birth year - XX: Encoded birth month, see below for encoding logic - DD: Birth day - SSS: Sequence number - C: Modulo-11 checksum digit. Not present for people born before 1954. The encoded month is MM for men, MM + 50 for women, and can be MM + 20 for men or MM + 70 for women when additional number ranges are needed. Older numbers for people born before 1954 can use YYXXDDSSS and do not use the modulo-11 checksum.              Only returned for Identify verifications.
     *
     * @return self
     */
    public function setBirthNumber($birth_number)
    {
        if (is_null($birth_number)) {
            array_push($this->openAPINullablesSetToNull, 'birth_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_number'] = $birth_number;

        return $this;
    }

    /**
     * Gets age
     *
     * @return int|null
     */
    public function getAge()
    {
        return $this->container['age'];
    }

    /**
     * Sets age
     *
     * @param int|null $age The individual's age.
     *
     * @return self
     */
    public function setAge($age)
    {
        if (is_null($age)) {
            array_push($this->openAPINullablesSetToNull, 'age');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('age', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['age'] = $age;

        return $this;
    }

    /**
     * Gets is_adult
     *
     * @return bool|null
     */
    public function getIsAdult()
    {
        return $this->container['is_adult'];
    }

    /**
     * Sets is_adult
     *
     * @param bool|null $is_adult Whether the individual is an adult.              In the Czech Republic, legal majority (adulthood) is reached at 18 years old. Only returned for Identify Plus verifications.
     *
     * @return self
     */
    public function setIsAdult($is_adult)
    {
        if (is_null($is_adult)) {
            array_push($this->openAPINullablesSetToNull, 'is_adult');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_adult', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_adult'] = $is_adult;

        return $this;
    }

    /**
     * Gets date_of_death
     *
     * @return \DateTime|null
     */
    public function getDateOfDeath()
    {
        return $this->container['date_of_death'];
    }

    /**
     * Sets date_of_death
     *
     * @param \DateTime|null $date_of_death The individual's date of death, if available.
     *
     * @return self
     */
    public function setDateOfDeath($date_of_death)
    {
        if (is_null($date_of_death)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_death');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_death', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_death'] = $date_of_death;

        return $this;
    }

    /**
     * Gets birth_place
     *
     * @return string|null
     */
    public function getBirthPlace()
    {
        return $this->container['birth_place'];
    }

    /**
     * Sets birth_place
     *
     * @param string|null $birth_place The individual's place of birth.              Only returned for Identify Plus verifications.
     *
     * @return self
     */
    public function setBirthPlace($birth_place)
    {
        if (is_null($birth_place)) {
            array_push($this->openAPINullablesSetToNull, 'birth_place');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_place', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_place'] = $birth_place;

        return $this;
    }

    /**
     * Gets birth_country
     *
     * @return string|null
     */
    public function getBirthCountry()
    {
        return $this->container['birth_country'];
    }

    /**
     * Sets birth_country
     *
     * @param string|null $birth_country The individual's country of birth.              Only returned for Identify Plus verifications.
     *
     * @return self
     */
    public function setBirthCountry($birth_country)
    {
        if (is_null($birth_country)) {
            array_push($this->openAPINullablesSetToNull, 'birth_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_country'] = $birth_country;

        return $this;
    }

    /**
     * Gets primary_nationality
     *
     * @return string|null
     */
    public function getPrimaryNationality()
    {
        return $this->container['primary_nationality'];
    }

    /**
     * Sets primary_nationality
     *
     * @param string|null $primary_nationality The individual's primary nationality.              The value is an ISO 3166-1 alpha-2 country code. Only returned for Identify Plus verifications.
     *
     * @return self
     */
    public function setPrimaryNationality($primary_nationality)
    {
        if (is_null($primary_nationality)) {
            array_push($this->openAPINullablesSetToNull, 'primary_nationality');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('primary_nationality', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['primary_nationality'] = $primary_nationality;

        return $this;
    }

    /**
     * Gets nationalities
     *
     * @return string[]|null
     */
    public function getNationalities()
    {
        return $this->container['nationalities'];
    }

    /**
     * Sets nationalities
     *
     * @param string[]|null $nationalities The individual's nationalities.
     *
     * @return self
     */
    public function setNationalities($nationalities)
    {
        if (is_null($nationalities)) {
            array_push($this->openAPINullablesSetToNull, 'nationalities');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nationalities', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nationalities'] = $nationalities;

        return $this;
    }

    /**
     * Gets marital_status
     *
     * @return string|null
     */
    public function getMaritalStatus()
    {
        return $this->container['marital_status'];
    }

    /**
     * Sets marital_status
     *
     * @param string|null $marital_status The individual's marital status.              Possible values: - COHABITATION - MARRIED - DIVORCED - REGISTERED_PARTNERSHIP - REGISTERED_PARTNERSHIP_CANCELED - WIDOWED - SINGLE - PARTNERSHIP - PARTNERSHIP_CANCELED - SEPARATED - REGISTERED_PARTNERSHIP_WIDOWED - LAPSED_MARRIAGE - UNKNOWN              Only returned for Identify Plus verifications.
     *
     * @return self
     */
    public function setMaritalStatus($marital_status)
    {
        if (is_null($marital_status)) {
            array_push($this->openAPINullablesSetToNull, 'marital_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('marital_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['marital_status'] = $marital_status;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email The individual's email address.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets email_verified
     *
     * @return bool|null
     */
    public function getEmailVerified()
    {
        return $this->container['email_verified'];
    }

    /**
     * Sets email_verified
     *
     * @param bool|null $email_verified Whether the individual's email address has been verified.
     *
     * @return self
     */
    public function setEmailVerified($email_verified)
    {
        if (is_null($email_verified)) {
            array_push($this->openAPINullablesSetToNull, 'email_verified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email_verified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email_verified'] = $email_verified;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return string|null
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string|null $phone_number The individual's phone number.              This value is normalized to E.164 format.
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            array_push($this->openAPINullablesSetToNull, 'phone_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets phone_number_verified
     *
     * @return bool|null
     */
    public function getPhoneNumberVerified()
    {
        return $this->container['phone_number_verified'];
    }

    /**
     * Sets phone_number_verified
     *
     * @param bool|null $phone_number_verified Whether the individual's phone number has been verified.
     *
     * @return self
     */
    public function setPhoneNumberVerified($phone_number_verified)
    {
        if (is_null($phone_number_verified)) {
            array_push($this->openAPINullablesSetToNull, 'phone_number_verified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_number_verified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_number_verified'] = $phone_number_verified;

        return $this;
    }

    /**
     * Gets is_politically_exposed_person
     *
     * @return bool|null
     */
    public function getIsPoliticallyExposedPerson()
    {
        return $this->container['is_politically_exposed_person'];
    }

    /**
     * Sets is_politically_exposed_person
     *
     * @param bool|null $is_politically_exposed_person Whether the individual is a politically exposed person.              This follows Czech anti-money-laundering rules, indicating a person that is at risk for corruption, bribery or money laundering activities. Mandatory screening of these individuals is required for compliance. Typically set for people such as the Prime Minister, ministers, etc.
     *
     * @return self
     */
    public function setIsPoliticallyExposedPerson($is_politically_exposed_person)
    {
        if (is_null($is_politically_exposed_person)) {
            array_push($this->openAPINullablesSetToNull, 'is_politically_exposed_person');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('is_politically_exposed_person', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['is_politically_exposed_person'] = $is_politically_exposed_person;

        return $this;
    }

    /**
     * Gets limited_legal_capacity
     *
     * @return bool|null
     */
    public function getLimitedLegalCapacity()
    {
        return $this->container['limited_legal_capacity'];
    }

    /**
     * Sets limited_legal_capacity
     *
     * @param bool|null $limited_legal_capacity Whether the individual is a person with limited legal capacity.
     *
     * @return self
     */
    public function setLimitedLegalCapacity($limited_legal_capacity)
    {
        if (is_null($limited_legal_capacity)) {
            array_push($this->openAPINullablesSetToNull, 'limited_legal_capacity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('limited_legal_capacity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['limited_legal_capacity'] = $limited_legal_capacity;

        return $this;
    }

    /**
     * Gets verification
     *
     * @return \Trinsic\Api\Model\CzechBankIdVerification|null
     */
    public function getVerification()
    {
        return $this->container['verification'];
    }

    /**
     * Sets verification
     *
     * @param \Trinsic\Api\Model\CzechBankIdVerification|null $verification Metadata about how the identity information was verified for Anti Money Laundering scope.              Only returned for Identify AML verifications.
     *
     * @return self
     */
    public function setVerification($verification)
    {
        if (is_null($verification)) {
            array_push($this->openAPINullablesSetToNull, 'verification');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('verification', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['verification'] = $verification;

        return $this;
    }

    /**
     * Gets addresses
     *
     * @return \Trinsic\Api\Model\CzechBankIdAddress[]|null
     */
    public function getAddresses()
    {
        return $this->container['addresses'];
    }

    /**
     * Sets addresses
     *
     * @param \Trinsic\Api\Model\CzechBankIdAddress[]|null $addresses The individual's addresses.              This can include permanent residence and contact addresses. Only returned for Identify verifications.
     *
     * @return self
     */
    public function setAddresses($addresses)
    {
        if (is_null($addresses)) {
            array_push($this->openAPINullablesSetToNull, 'addresses');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('addresses', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['addresses'] = $addresses;

        return $this;
    }

    /**
     * Gets id_cards
     *
     * @return \Trinsic\Api\Model\CzechBankIdCard[]|null
     */
    public function getIdCards()
    {
        return $this->container['id_cards'];
    }

    /**
     * Sets id_cards
     *
     * @param \Trinsic\Api\Model\CzechBankIdCard[]|null $id_cards The individual's identity documents.              This can include document type, country, number, issuer, and validity dates. Only returned for Identify Plus verifications.
     *
     * @return self
     */
    public function setIdCards($id_cards)
    {
        if (is_null($id_cards)) {
            array_push($this->openAPINullablesSetToNull, 'id_cards');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id_cards', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id_cards'] = $id_cards;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at The UTC date and time when the identity data was last updated.
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            array_push($this->openAPINullablesSetToNull, 'updated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updated_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets zone_info
     *
     * @return string|null
     */
    public function getZoneInfo()
    {
        return $this->container['zone_info'];
    }

    /**
     * Sets zone_info
     *
     * @param string|null $zone_info The individual's time zone.              This is represented as a zoneinfo/IANA Time Zone Database value.
     *
     * @return self
     */
    public function setZoneInfo($zone_info)
    {
        if (is_null($zone_info)) {
            array_push($this->openAPINullablesSetToNull, 'zone_info');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('zone_info', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['zone_info'] = $zone_info;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale The individual's locale.              This is represented as a BCP 47/RFC 5646 language tag. Some values may use an underscore separator, such as cs_CZ.
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            array_push($this->openAPINullablesSetToNull, 'locale');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('locale', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets titles
     *
     * @return \Trinsic\Api\Model\CzechBankIdTitle[]|null
     */
    public function getTitles()
    {
        return $this->container['titles'];
    }

    /**
     * Sets titles
     *
     * @param \Trinsic\Api\Model\CzechBankIdTitle[]|null $titles The individual's title prefixes and suffixes.              Only returned for Identify verifications.
     *
     * @return self
     */
    public function setTitles($titles)
    {
        if (is_null($titles)) {
            array_push($this->openAPINullablesSetToNull, 'titles');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('titles', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['titles'] = $titles;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


