<?php
/**
 * EvrotrustAddressComponents
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * EvrotrustAddressComponents Class Doc Comment
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class EvrotrustAddressComponents implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'EvrotrustAddressComponents';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'district' => 'string',
        'district_local' => 'string',
        'municipality' => 'string',
        'municipality_local' => 'string',
        'settlement' => 'string',
        'settlement_local' => 'string',
        'location' => 'string',
        'location_local' => 'string',
        'building_number' => 'string',
        'building_number_local' => 'string',
        'entrance' => 'string',
        'entrance_local' => 'string',
        'floor' => 'string',
        'floor_local' => 'string',
        'apartment' => 'string',
        'apartment_local' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'district' => null,
        'district_local' => null,
        'municipality' => null,
        'municipality_local' => null,
        'settlement' => null,
        'settlement_local' => null,
        'location' => null,
        'location_local' => null,
        'building_number' => null,
        'building_number_local' => null,
        'entrance' => null,
        'entrance_local' => null,
        'floor' => null,
        'floor_local' => null,
        'apartment' => null,
        'apartment_local' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'district' => true,
        'district_local' => true,
        'municipality' => true,
        'municipality_local' => true,
        'settlement' => true,
        'settlement_local' => true,
        'location' => true,
        'location_local' => true,
        'building_number' => true,
        'building_number_local' => true,
        'entrance' => true,
        'entrance_local' => true,
        'floor' => true,
        'floor_local' => true,
        'apartment' => true,
        'apartment_local' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'district' => 'district',
        'district_local' => 'districtLocal',
        'municipality' => 'municipality',
        'municipality_local' => 'municipalityLocal',
        'settlement' => 'settlement',
        'settlement_local' => 'settlementLocal',
        'location' => 'location',
        'location_local' => 'locationLocal',
        'building_number' => 'buildingNumber',
        'building_number_local' => 'buildingNumberLocal',
        'entrance' => 'entrance',
        'entrance_local' => 'entranceLocal',
        'floor' => 'floor',
        'floor_local' => 'floorLocal',
        'apartment' => 'apartment',
        'apartment_local' => 'apartmentLocal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'district' => 'setDistrict',
        'district_local' => 'setDistrictLocal',
        'municipality' => 'setMunicipality',
        'municipality_local' => 'setMunicipalityLocal',
        'settlement' => 'setSettlement',
        'settlement_local' => 'setSettlementLocal',
        'location' => 'setLocation',
        'location_local' => 'setLocationLocal',
        'building_number' => 'setBuildingNumber',
        'building_number_local' => 'setBuildingNumberLocal',
        'entrance' => 'setEntrance',
        'entrance_local' => 'setEntranceLocal',
        'floor' => 'setFloor',
        'floor_local' => 'setFloorLocal',
        'apartment' => 'setApartment',
        'apartment_local' => 'setApartmentLocal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'district' => 'getDistrict',
        'district_local' => 'getDistrictLocal',
        'municipality' => 'getMunicipality',
        'municipality_local' => 'getMunicipalityLocal',
        'settlement' => 'getSettlement',
        'settlement_local' => 'getSettlementLocal',
        'location' => 'getLocation',
        'location_local' => 'getLocationLocal',
        'building_number' => 'getBuildingNumber',
        'building_number_local' => 'getBuildingNumberLocal',
        'entrance' => 'getEntrance',
        'entrance_local' => 'getEntranceLocal',
        'floor' => 'getFloor',
        'floor_local' => 'getFloorLocal',
        'apartment' => 'getApartment',
        'apartment_local' => 'getApartmentLocal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('district', $data ?? [], null);
        $this->setIfExists('district_local', $data ?? [], null);
        $this->setIfExists('municipality', $data ?? [], null);
        $this->setIfExists('municipality_local', $data ?? [], null);
        $this->setIfExists('settlement', $data ?? [], null);
        $this->setIfExists('settlement_local', $data ?? [], null);
        $this->setIfExists('location', $data ?? [], null);
        $this->setIfExists('location_local', $data ?? [], null);
        $this->setIfExists('building_number', $data ?? [], null);
        $this->setIfExists('building_number_local', $data ?? [], null);
        $this->setIfExists('entrance', $data ?? [], null);
        $this->setIfExists('entrance_local', $data ?? [], null);
        $this->setIfExists('floor', $data ?? [], null);
        $this->setIfExists('floor_local', $data ?? [], null);
        $this->setIfExists('apartment', $data ?? [], null);
        $this->setIfExists('apartment_local', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets district
     *
     * @return string|null
     */
    public function getDistrict()
    {
        return $this->container['district'];
    }

    /**
     * Sets district
     *
     * @param string|null $district The district fragment of the address.
     *
     * @return self
     */
    public function setDistrict($district)
    {
        if (is_null($district)) {
            array_push($this->openAPINullablesSetToNull, 'district');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('district', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['district'] = $district;

        return $this;
    }

    /**
     * Gets district_local
     *
     * @return string|null
     */
    public function getDistrictLocal()
    {
        return $this->container['district_local'];
    }

    /**
     * Sets district_local
     *
     * @param string|null $district_local The local-language district fragment of the address.
     *
     * @return self
     */
    public function setDistrictLocal($district_local)
    {
        if (is_null($district_local)) {
            array_push($this->openAPINullablesSetToNull, 'district_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('district_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['district_local'] = $district_local;

        return $this;
    }

    /**
     * Gets municipality
     *
     * @return string|null
     */
    public function getMunicipality()
    {
        return $this->container['municipality'];
    }

    /**
     * Sets municipality
     *
     * @param string|null $municipality The municipality fragment of the address.
     *
     * @return self
     */
    public function setMunicipality($municipality)
    {
        if (is_null($municipality)) {
            array_push($this->openAPINullablesSetToNull, 'municipality');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('municipality', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['municipality'] = $municipality;

        return $this;
    }

    /**
     * Gets municipality_local
     *
     * @return string|null
     */
    public function getMunicipalityLocal()
    {
        return $this->container['municipality_local'];
    }

    /**
     * Sets municipality_local
     *
     * @param string|null $municipality_local The local-language municipality fragment of the address.
     *
     * @return self
     */
    public function setMunicipalityLocal($municipality_local)
    {
        if (is_null($municipality_local)) {
            array_push($this->openAPINullablesSetToNull, 'municipality_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('municipality_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['municipality_local'] = $municipality_local;

        return $this;
    }

    /**
     * Gets settlement
     *
     * @return string|null
     */
    public function getSettlement()
    {
        return $this->container['settlement'];
    }

    /**
     * Sets settlement
     *
     * @param string|null $settlement The settlement fragment of the address.
     *
     * @return self
     */
    public function setSettlement($settlement)
    {
        if (is_null($settlement)) {
            array_push($this->openAPINullablesSetToNull, 'settlement');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('settlement', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['settlement'] = $settlement;

        return $this;
    }

    /**
     * Gets settlement_local
     *
     * @return string|null
     */
    public function getSettlementLocal()
    {
        return $this->container['settlement_local'];
    }

    /**
     * Sets settlement_local
     *
     * @param string|null $settlement_local The local-language settlement fragment of the address.
     *
     * @return self
     */
    public function setSettlementLocal($settlement_local)
    {
        if (is_null($settlement_local)) {
            array_push($this->openAPINullablesSetToNull, 'settlement_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('settlement_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['settlement_local'] = $settlement_local;

        return $this;
    }

    /**
     * Gets location
     *
     * @return string|null
     */
    public function getLocation()
    {
        return $this->container['location'];
    }

    /**
     * Sets location
     *
     * @param string|null $location The location or street fragment of the address.
     *
     * @return self
     */
    public function setLocation($location)
    {
        if (is_null($location)) {
            array_push($this->openAPINullablesSetToNull, 'location');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('location', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['location'] = $location;

        return $this;
    }

    /**
     * Gets location_local
     *
     * @return string|null
     */
    public function getLocationLocal()
    {
        return $this->container['location_local'];
    }

    /**
     * Sets location_local
     *
     * @param string|null $location_local The local-language location or street fragment of the address.
     *
     * @return self
     */
    public function setLocationLocal($location_local)
    {
        if (is_null($location_local)) {
            array_push($this->openAPINullablesSetToNull, 'location_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('location_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['location_local'] = $location_local;

        return $this;
    }

    /**
     * Gets building_number
     *
     * @return string|null
     */
    public function getBuildingNumber()
    {
        return $this->container['building_number'];
    }

    /**
     * Sets building_number
     *
     * @param string|null $building_number The building number fragment of the address.
     *
     * @return self
     */
    public function setBuildingNumber($building_number)
    {
        if (is_null($building_number)) {
            array_push($this->openAPINullablesSetToNull, 'building_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('building_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['building_number'] = $building_number;

        return $this;
    }

    /**
     * Gets building_number_local
     *
     * @return string|null
     */
    public function getBuildingNumberLocal()
    {
        return $this->container['building_number_local'];
    }

    /**
     * Sets building_number_local
     *
     * @param string|null $building_number_local The local-language building number fragment of the address.
     *
     * @return self
     */
    public function setBuildingNumberLocal($building_number_local)
    {
        if (is_null($building_number_local)) {
            array_push($this->openAPINullablesSetToNull, 'building_number_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('building_number_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['building_number_local'] = $building_number_local;

        return $this;
    }

    /**
     * Gets entrance
     *
     * @return string|null
     */
    public function getEntrance()
    {
        return $this->container['entrance'];
    }

    /**
     * Sets entrance
     *
     * @param string|null $entrance The entrance fragment of the address.
     *
     * @return self
     */
    public function setEntrance($entrance)
    {
        if (is_null($entrance)) {
            array_push($this->openAPINullablesSetToNull, 'entrance');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entrance', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['entrance'] = $entrance;

        return $this;
    }

    /**
     * Gets entrance_local
     *
     * @return string|null
     */
    public function getEntranceLocal()
    {
        return $this->container['entrance_local'];
    }

    /**
     * Sets entrance_local
     *
     * @param string|null $entrance_local The local-language entrance fragment of the address.
     *
     * @return self
     */
    public function setEntranceLocal($entrance_local)
    {
        if (is_null($entrance_local)) {
            array_push($this->openAPINullablesSetToNull, 'entrance_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('entrance_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['entrance_local'] = $entrance_local;

        return $this;
    }

    /**
     * Gets floor
     *
     * @return string|null
     */
    public function getFloor()
    {
        return $this->container['floor'];
    }

    /**
     * Sets floor
     *
     * @param string|null $floor The floor fragment of the address.
     *
     * @return self
     */
    public function setFloor($floor)
    {
        if (is_null($floor)) {
            array_push($this->openAPINullablesSetToNull, 'floor');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('floor', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['floor'] = $floor;

        return $this;
    }

    /**
     * Gets floor_local
     *
     * @return string|null
     */
    public function getFloorLocal()
    {
        return $this->container['floor_local'];
    }

    /**
     * Sets floor_local
     *
     * @param string|null $floor_local The local-language floor fragment of the address.
     *
     * @return self
     */
    public function setFloorLocal($floor_local)
    {
        if (is_null($floor_local)) {
            array_push($this->openAPINullablesSetToNull, 'floor_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('floor_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['floor_local'] = $floor_local;

        return $this;
    }

    /**
     * Gets apartment
     *
     * @return string|null
     */
    public function getApartment()
    {
        return $this->container['apartment'];
    }

    /**
     * Sets apartment
     *
     * @param string|null $apartment The apartment fragment of the address.
     *
     * @return self
     */
    public function setApartment($apartment)
    {
        if (is_null($apartment)) {
            array_push($this->openAPINullablesSetToNull, 'apartment');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apartment', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apartment'] = $apartment;

        return $this;
    }

    /**
     * Gets apartment_local
     *
     * @return string|null
     */
    public function getApartmentLocal()
    {
        return $this->container['apartment_local'];
    }

    /**
     * Sets apartment_local
     *
     * @param string|null $apartment_local The local-language apartment fragment of the address.
     *
     * @return self
     */
    public function setApartmentLocal($apartment_local)
    {
        if (is_null($apartment_local)) {
            array_push($this->openAPINullablesSetToNull, 'apartment_local');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('apartment_local', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['apartment_local'] = $apartment_local;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


