<?php
/**
 * IdemiaMobileIdProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * IdemiaMobileIdProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for Idemia Mobile ID Providers which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IdemiaMobileIdProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'IdemiaMobileIdProviderOutput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'sub' => 'string',
        'name_suffix' => 'string',
        'full_name' => 'string',
        'given_name' => 'string',
        'family_name' => 'string',
        'birth_date' => 'string',
        'age_over18' => 'string',
        'age_over21' => 'string',
        'age_over25' => 'string',
        'resident_address' => 'string',
        'resident_state' => 'string',
        'resident_country' => 'string',
        'resident_postal_code' => 'string',
        'resident_city' => 'string',
        'email' => 'string',
        'email_verified' => 'bool',
        'document_number' => 'string',
        'issue_date' => 'string',
        'issuing_country' => 'string',
        'issuing_authority' => 'string',
        'expiry_date' => 'string',
        'issuing_jurisdiction' => 'string',
        'document_type' => 'string',
        'sex' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'sub' => null,
        'name_suffix' => null,
        'full_name' => null,
        'given_name' => null,
        'family_name' => null,
        'birth_date' => null,
        'age_over18' => null,
        'age_over21' => null,
        'age_over25' => null,
        'resident_address' => null,
        'resident_state' => null,
        'resident_country' => null,
        'resident_postal_code' => null,
        'resident_city' => null,
        'email' => null,
        'email_verified' => null,
        'document_number' => null,
        'issue_date' => null,
        'issuing_country' => null,
        'issuing_authority' => null,
        'expiry_date' => null,
        'issuing_jurisdiction' => null,
        'document_type' => null,
        'sex' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'sub' => true,
        'name_suffix' => true,
        'full_name' => true,
        'given_name' => true,
        'family_name' => true,
        'birth_date' => true,
        'age_over18' => true,
        'age_over21' => true,
        'age_over25' => true,
        'resident_address' => true,
        'resident_state' => true,
        'resident_country' => true,
        'resident_postal_code' => true,
        'resident_city' => true,
        'email' => true,
        'email_verified' => true,
        'document_number' => true,
        'issue_date' => true,
        'issuing_country' => true,
        'issuing_authority' => true,
        'expiry_date' => true,
        'issuing_jurisdiction' => true,
        'document_type' => true,
        'sex' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'sub' => 'sub',
        'name_suffix' => 'nameSuffix',
        'full_name' => 'fullName',
        'given_name' => 'givenName',
        'family_name' => 'familyName',
        'birth_date' => 'birthDate',
        'age_over18' => 'ageOver18',
        'age_over21' => 'ageOver21',
        'age_over25' => 'ageOver25',
        'resident_address' => 'residentAddress',
        'resident_state' => 'residentState',
        'resident_country' => 'residentCountry',
        'resident_postal_code' => 'residentPostalCode',
        'resident_city' => 'residentCity',
        'email' => 'email',
        'email_verified' => 'emailVerified',
        'document_number' => 'documentNumber',
        'issue_date' => 'issueDate',
        'issuing_country' => 'issuingCountry',
        'issuing_authority' => 'issuingAuthority',
        'expiry_date' => 'expiryDate',
        'issuing_jurisdiction' => 'issuingJurisdiction',
        'document_type' => 'documentType',
        'sex' => 'sex'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'sub' => 'setSub',
        'name_suffix' => 'setNameSuffix',
        'full_name' => 'setFullName',
        'given_name' => 'setGivenName',
        'family_name' => 'setFamilyName',
        'birth_date' => 'setBirthDate',
        'age_over18' => 'setAgeOver18',
        'age_over21' => 'setAgeOver21',
        'age_over25' => 'setAgeOver25',
        'resident_address' => 'setResidentAddress',
        'resident_state' => 'setResidentState',
        'resident_country' => 'setResidentCountry',
        'resident_postal_code' => 'setResidentPostalCode',
        'resident_city' => 'setResidentCity',
        'email' => 'setEmail',
        'email_verified' => 'setEmailVerified',
        'document_number' => 'setDocumentNumber',
        'issue_date' => 'setIssueDate',
        'issuing_country' => 'setIssuingCountry',
        'issuing_authority' => 'setIssuingAuthority',
        'expiry_date' => 'setExpiryDate',
        'issuing_jurisdiction' => 'setIssuingJurisdiction',
        'document_type' => 'setDocumentType',
        'sex' => 'setSex'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'sub' => 'getSub',
        'name_suffix' => 'getNameSuffix',
        'full_name' => 'getFullName',
        'given_name' => 'getGivenName',
        'family_name' => 'getFamilyName',
        'birth_date' => 'getBirthDate',
        'age_over18' => 'getAgeOver18',
        'age_over21' => 'getAgeOver21',
        'age_over25' => 'getAgeOver25',
        'resident_address' => 'getResidentAddress',
        'resident_state' => 'getResidentState',
        'resident_country' => 'getResidentCountry',
        'resident_postal_code' => 'getResidentPostalCode',
        'resident_city' => 'getResidentCity',
        'email' => 'getEmail',
        'email_verified' => 'getEmailVerified',
        'document_number' => 'getDocumentNumber',
        'issue_date' => 'getIssueDate',
        'issuing_country' => 'getIssuingCountry',
        'issuing_authority' => 'getIssuingAuthority',
        'expiry_date' => 'getExpiryDate',
        'issuing_jurisdiction' => 'getIssuingJurisdiction',
        'document_type' => 'getDocumentType',
        'sex' => 'getSex'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('sub', $data ?? [], null);
        $this->setIfExists('name_suffix', $data ?? [], null);
        $this->setIfExists('full_name', $data ?? [], null);
        $this->setIfExists('given_name', $data ?? [], null);
        $this->setIfExists('family_name', $data ?? [], null);
        $this->setIfExists('birth_date', $data ?? [], null);
        $this->setIfExists('age_over18', $data ?? [], null);
        $this->setIfExists('age_over21', $data ?? [], null);
        $this->setIfExists('age_over25', $data ?? [], null);
        $this->setIfExists('resident_address', $data ?? [], null);
        $this->setIfExists('resident_state', $data ?? [], null);
        $this->setIfExists('resident_country', $data ?? [], null);
        $this->setIfExists('resident_postal_code', $data ?? [], null);
        $this->setIfExists('resident_city', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('email_verified', $data ?? [], null);
        $this->setIfExists('document_number', $data ?? [], null);
        $this->setIfExists('issue_date', $data ?? [], null);
        $this->setIfExists('issuing_country', $data ?? [], null);
        $this->setIfExists('issuing_authority', $data ?? [], null);
        $this->setIfExists('expiry_date', $data ?? [], null);
        $this->setIfExists('issuing_jurisdiction', $data ?? [], null);
        $this->setIfExists('document_type', $data ?? [], null);
        $this->setIfExists('sex', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets sub
     *
     * @return string|null
     */
    public function getSub()
    {
        return $this->container['sub'];
    }

    /**
     * Sets sub
     *
     * @param string|null $sub The OpenID Connect subject identifier for the verified individual.
     *
     * @return self
     */
    public function setSub($sub)
    {
        if (is_null($sub)) {
            array_push($this->openAPINullablesSetToNull, 'sub');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sub', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sub'] = $sub;

        return $this;
    }

    /**
     * Gets name_suffix
     *
     * @return string|null
     */
    public function getNameSuffix()
    {
        return $this->container['name_suffix'];
    }

    /**
     * Sets name_suffix
     *
     * @param string|null $name_suffix The individual's name suffix.
     *
     * @return self
     */
    public function setNameSuffix($name_suffix)
    {
        if (is_null($name_suffix)) {
            array_push($this->openAPINullablesSetToNull, 'name_suffix');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name_suffix', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name_suffix'] = $name_suffix;

        return $this;
    }

    /**
     * Gets full_name
     *
     * @return string|null
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     *
     * @param string|null $full_name The individual's full name.
     *
     * @return self
     */
    public function setFullName($full_name)
    {
        if (is_null($full_name)) {
            array_push($this->openAPINullablesSetToNull, 'full_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('full_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets given_name
     *
     * @return string|null
     */
    public function getGivenName()
    {
        return $this->container['given_name'];
    }

    /**
     * Sets given_name
     *
     * @param string|null $given_name The individual's given name.
     *
     * @return self
     */
    public function setGivenName($given_name)
    {
        if (is_null($given_name)) {
            array_push($this->openAPINullablesSetToNull, 'given_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('given_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['given_name'] = $given_name;

        return $this;
    }

    /**
     * Gets family_name
     *
     * @return string|null
     */
    public function getFamilyName()
    {
        return $this->container['family_name'];
    }

    /**
     * Sets family_name
     *
     * @param string|null $family_name The individual's family name.
     *
     * @return self
     */
    public function setFamilyName($family_name)
    {
        if (is_null($family_name)) {
            array_push($this->openAPINullablesSetToNull, 'family_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('family_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['family_name'] = $family_name;

        return $this;
    }

    /**
     * Gets birth_date
     *
     * @return string|null
     */
    public function getBirthDate()
    {
        return $this->container['birth_date'];
    }

    /**
     * Sets birth_date
     *
     * @param string|null $birth_date The individual's birth date.
     *
     * @return self
     */
    public function setBirthDate($birth_date)
    {
        if (is_null($birth_date)) {
            array_push($this->openAPINullablesSetToNull, 'birth_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('birth_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['birth_date'] = $birth_date;

        return $this;
    }

    /**
     * Gets age_over18
     *
     * @return string|null
     */
    public function getAgeOver18()
    {
        return $this->container['age_over18'];
    }

    /**
     * Sets age_over18
     *
     * @param string|null $age_over18 Whether the individual is over 18 years old.
     *
     * @return self
     */
    public function setAgeOver18($age_over18)
    {
        if (is_null($age_over18)) {
            array_push($this->openAPINullablesSetToNull, 'age_over18');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('age_over18', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['age_over18'] = $age_over18;

        return $this;
    }

    /**
     * Gets age_over21
     *
     * @return string|null
     */
    public function getAgeOver21()
    {
        return $this->container['age_over21'];
    }

    /**
     * Sets age_over21
     *
     * @param string|null $age_over21 Whether the individual is over 21 years old.
     *
     * @return self
     */
    public function setAgeOver21($age_over21)
    {
        if (is_null($age_over21)) {
            array_push($this->openAPINullablesSetToNull, 'age_over21');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('age_over21', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['age_over21'] = $age_over21;

        return $this;
    }

    /**
     * Gets age_over25
     *
     * @return string|null
     */
    public function getAgeOver25()
    {
        return $this->container['age_over25'];
    }

    /**
     * Sets age_over25
     *
     * @param string|null $age_over25 Whether the individual is over 25 years old.
     *
     * @return self
     */
    public function setAgeOver25($age_over25)
    {
        if (is_null($age_over25)) {
            array_push($this->openAPINullablesSetToNull, 'age_over25');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('age_over25', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['age_over25'] = $age_over25;

        return $this;
    }

    /**
     * Gets resident_address
     *
     * @return string|null
     */
    public function getResidentAddress()
    {
        return $this->container['resident_address'];
    }

    /**
     * Sets resident_address
     *
     * @param string|null $resident_address The individual's resident street address.
     *
     * @return self
     */
    public function setResidentAddress($resident_address)
    {
        if (is_null($resident_address)) {
            array_push($this->openAPINullablesSetToNull, 'resident_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_address'] = $resident_address;

        return $this;
    }

    /**
     * Gets resident_state
     *
     * @return string|null
     */
    public function getResidentState()
    {
        return $this->container['resident_state'];
    }

    /**
     * Sets resident_state
     *
     * @param string|null $resident_state The individual's resident state.
     *
     * @return self
     */
    public function setResidentState($resident_state)
    {
        if (is_null($resident_state)) {
            array_push($this->openAPINullablesSetToNull, 'resident_state');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_state', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_state'] = $resident_state;

        return $this;
    }

    /**
     * Gets resident_country
     *
     * @return string|null
     */
    public function getResidentCountry()
    {
        return $this->container['resident_country'];
    }

    /**
     * Sets resident_country
     *
     * @param string|null $resident_country The individual's resident country.
     *
     * @return self
     */
    public function setResidentCountry($resident_country)
    {
        if (is_null($resident_country)) {
            array_push($this->openAPINullablesSetToNull, 'resident_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_country'] = $resident_country;

        return $this;
    }

    /**
     * Gets resident_postal_code
     *
     * @return string|null
     */
    public function getResidentPostalCode()
    {
        return $this->container['resident_postal_code'];
    }

    /**
     * Sets resident_postal_code
     *
     * @param string|null $resident_postal_code The individual's resident postal code.
     *
     * @return self
     */
    public function setResidentPostalCode($resident_postal_code)
    {
        if (is_null($resident_postal_code)) {
            array_push($this->openAPINullablesSetToNull, 'resident_postal_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_postal_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_postal_code'] = $resident_postal_code;

        return $this;
    }

    /**
     * Gets resident_city
     *
     * @return string|null
     */
    public function getResidentCity()
    {
        return $this->container['resident_city'];
    }

    /**
     * Sets resident_city
     *
     * @param string|null $resident_city The individual's resident city.
     *
     * @return self
     */
    public function setResidentCity($resident_city)
    {
        if (is_null($resident_city)) {
            array_push($this->openAPINullablesSetToNull, 'resident_city');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_city', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_city'] = $resident_city;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email The individual's email address.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets email_verified
     *
     * @return bool|null
     */
    public function getEmailVerified()
    {
        return $this->container['email_verified'];
    }

    /**
     * Sets email_verified
     *
     * @param bool|null $email_verified Whether the individual's email address has been verified.
     *
     * @return self
     */
    public function setEmailVerified($email_verified)
    {
        if (is_null($email_verified)) {
            array_push($this->openAPINullablesSetToNull, 'email_verified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email_verified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email_verified'] = $email_verified;

        return $this;
    }

    /**
     * Gets document_number
     *
     * @return string|null
     */
    public function getDocumentNumber()
    {
        return $this->container['document_number'];
    }

    /**
     * Sets document_number
     *
     * @param string|null $document_number The individual's document number.
     *
     * @return self
     */
    public function setDocumentNumber($document_number)
    {
        if (is_null($document_number)) {
            array_push($this->openAPINullablesSetToNull, 'document_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_number'] = $document_number;

        return $this;
    }

    /**
     * Gets issue_date
     *
     * @return string|null
     */
    public function getIssueDate()
    {
        return $this->container['issue_date'];
    }

    /**
     * Sets issue_date
     *
     * @param string|null $issue_date The date the document was issued.
     *
     * @return self
     */
    public function setIssueDate($issue_date)
    {
        if (is_null($issue_date)) {
            array_push($this->openAPINullablesSetToNull, 'issue_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issue_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issue_date'] = $issue_date;

        return $this;
    }

    /**
     * Gets issuing_country
     *
     * @return string|null
     */
    public function getIssuingCountry()
    {
        return $this->container['issuing_country'];
    }

    /**
     * Sets issuing_country
     *
     * @param string|null $issuing_country The country that issued the document.
     *
     * @return self
     */
    public function setIssuingCountry($issuing_country)
    {
        if (is_null($issuing_country)) {
            array_push($this->openAPINullablesSetToNull, 'issuing_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issuing_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issuing_country'] = $issuing_country;

        return $this;
    }

    /**
     * Gets issuing_authority
     *
     * @return string|null
     */
    public function getIssuingAuthority()
    {
        return $this->container['issuing_authority'];
    }

    /**
     * Sets issuing_authority
     *
     * @param string|null $issuing_authority The authority that issued the document.
     *
     * @return self
     */
    public function setIssuingAuthority($issuing_authority)
    {
        if (is_null($issuing_authority)) {
            array_push($this->openAPINullablesSetToNull, 'issuing_authority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issuing_authority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issuing_authority'] = $issuing_authority;

        return $this;
    }

    /**
     * Gets expiry_date
     *
     * @return string|null
     */
    public function getExpiryDate()
    {
        return $this->container['expiry_date'];
    }

    /**
     * Sets expiry_date
     *
     * @param string|null $expiry_date The date the document expires.
     *
     * @return self
     */
    public function setExpiryDate($expiry_date)
    {
        if (is_null($expiry_date)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expiry_date'] = $expiry_date;

        return $this;
    }

    /**
     * Gets issuing_jurisdiction
     *
     * @return string|null
     */
    public function getIssuingJurisdiction()
    {
        return $this->container['issuing_jurisdiction'];
    }

    /**
     * Sets issuing_jurisdiction
     *
     * @param string|null $issuing_jurisdiction The jurisdiction that issued the document.
     *
     * @return self
     */
    public function setIssuingJurisdiction($issuing_jurisdiction)
    {
        if (is_null($issuing_jurisdiction)) {
            array_push($this->openAPINullablesSetToNull, 'issuing_jurisdiction');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issuing_jurisdiction', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issuing_jurisdiction'] = $issuing_jurisdiction;

        return $this;
    }

    /**
     * Gets document_type
     *
     * @return string|null
     */
    public function getDocumentType()
    {
        return $this->container['document_type'];
    }

    /**
     * Sets document_type
     *
     * @param string|null $document_type The document type.
     *
     * @return self
     */
    public function setDocumentType($document_type)
    {
        if (is_null($document_type)) {
            array_push($this->openAPINullablesSetToNull, 'document_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_type'] = $document_type;

        return $this;
    }

    /**
     * Gets sex
     *
     * @return string|null
     */
    public function getSex()
    {
        return $this->container['sex'];
    }

    /**
     * Sets sex
     *
     * @param string|null $sex The individual's sex.
     *
     * @return self
     */
    public function setSex($sex)
    {
        if (is_null($sex)) {
            array_push($this->openAPINullablesSetToNull, 'sex');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sex', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sex'] = $sex;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


