<?php
/**
 * IndonesiaDukcapilMatchProviderOutput
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * IndonesiaDukcapilMatchProviderOutput Class Doc Comment
 *
 * @category Class
 * @description Exposed properties for the &#x60;indonesia-dukcapil-match&#x60; Provider which do not directly map to the normalized IdentityData model.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class IndonesiaDukcapilMatchProviderOutput implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'IndonesiaDukcapilMatchProviderOutput';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'national_id_number' => '\Trinsic\Api\Model\IndonesiaDukcapilMatchNationalIdNumberField',
        'full_name' => '\Trinsic\Api\Model\IndonesiaDukcapilMatchFullNameField',
        'date_of_birth' => '\Trinsic\Api\Model\IndonesiaDukcapilMatchDateOfBirthField',
        'province_code' => 'string',
        'regency_or_city_code' => 'string',
        'district_code' => 'string',
        'sex_national_id_number' => 'string',
        'serial_number' => 'string',
        'phone_number' => 'string',
        'consent_given_at' => '\DateTime',
        'email' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'national_id_number' => null,
        'full_name' => null,
        'date_of_birth' => null,
        'province_code' => null,
        'regency_or_city_code' => null,
        'district_code' => null,
        'sex_national_id_number' => null,
        'serial_number' => null,
        'phone_number' => null,
        'consent_given_at' => 'date-time',
        'email' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'national_id_number' => true,
        'full_name' => true,
        'date_of_birth' => true,
        'province_code' => true,
        'regency_or_city_code' => true,
        'district_code' => true,
        'sex_national_id_number' => true,
        'serial_number' => true,
        'phone_number' => true,
        'consent_given_at' => true,
        'email' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'national_id_number' => 'nationalIdNumber',
        'full_name' => 'fullName',
        'date_of_birth' => 'dateOfBirth',
        'province_code' => 'provinceCode',
        'regency_or_city_code' => 'regencyOrCityCode',
        'district_code' => 'districtCode',
        'sex_national_id_number' => 'sexNationalIdNumber',
        'serial_number' => 'serialNumber',
        'phone_number' => 'phoneNumber',
        'consent_given_at' => 'consentGivenAt',
        'email' => 'email'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'national_id_number' => 'setNationalIdNumber',
        'full_name' => 'setFullName',
        'date_of_birth' => 'setDateOfBirth',
        'province_code' => 'setProvinceCode',
        'regency_or_city_code' => 'setRegencyOrCityCode',
        'district_code' => 'setDistrictCode',
        'sex_national_id_number' => 'setSexNationalIdNumber',
        'serial_number' => 'setSerialNumber',
        'phone_number' => 'setPhoneNumber',
        'consent_given_at' => 'setConsentGivenAt',
        'email' => 'setEmail'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'national_id_number' => 'getNationalIdNumber',
        'full_name' => 'getFullName',
        'date_of_birth' => 'getDateOfBirth',
        'province_code' => 'getProvinceCode',
        'regency_or_city_code' => 'getRegencyOrCityCode',
        'district_code' => 'getDistrictCode',
        'sex_national_id_number' => 'getSexNationalIdNumber',
        'serial_number' => 'getSerialNumber',
        'phone_number' => 'getPhoneNumber',
        'consent_given_at' => 'getConsentGivenAt',
        'email' => 'getEmail'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('national_id_number', $data ?? [], null);
        $this->setIfExists('full_name', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('province_code', $data ?? [], null);
        $this->setIfExists('regency_or_city_code', $data ?? [], null);
        $this->setIfExists('district_code', $data ?? [], null);
        $this->setIfExists('sex_national_id_number', $data ?? [], null);
        $this->setIfExists('serial_number', $data ?? [], null);
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('consent_given_at', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets national_id_number
     *
     * @return \Trinsic\Api\Model\IndonesiaDukcapilMatchNationalIdNumberField|null
     */
    public function getNationalIdNumber()
    {
        return $this->container['national_id_number'];
    }

    /**
     * Sets national_id_number
     *
     * @param \Trinsic\Api\Model\IndonesiaDukcapilMatchNationalIdNumberField|null $national_id_number NIK submitted for this Dukcapil match and the assessment result returned for that value.
     *
     * @return self
     */
    public function setNationalIdNumber($national_id_number)
    {
        if (is_null($national_id_number)) {
            array_push($this->openAPINullablesSetToNull, 'national_id_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('national_id_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['national_id_number'] = $national_id_number;

        return $this;
    }

    /**
     * Gets full_name
     *
     * @return \Trinsic\Api\Model\IndonesiaDukcapilMatchFullNameField|null
     */
    public function getFullName()
    {
        return $this->container['full_name'];
    }

    /**
     * Sets full_name
     *
     * @param \Trinsic\Api\Model\IndonesiaDukcapilMatchFullNameField|null $full_name Full name submitted for this Dukcapil match and the assessment result returned for that value.
     *
     * @return self
     */
    public function setFullName($full_name)
    {
        if (is_null($full_name)) {
            array_push($this->openAPINullablesSetToNull, 'full_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('full_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['full_name'] = $full_name;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return \Trinsic\Api\Model\IndonesiaDukcapilMatchDateOfBirthField|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param \Trinsic\Api\Model\IndonesiaDukcapilMatchDateOfBirthField|null $date_of_birth Date of birth submitted for this Dukcapil match and the assessment result returned for that value.
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_birth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_birth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets province_code
     *
     * @return string|null
     */
    public function getProvinceCode()
    {
        return $this->container['province_code'];
    }

    /**
     * Sets province_code
     *
     * @param string|null $province_code Two-digit Indonesian government administrative region code for the province, extracted from digits 1-2 of the submitted NIK number.              Source system: Kode Wilayah Administrasi Pemerintahan, maintained by Indonesia's Ministry of Home Affairs. The first digit indicates the island group: 1-2 Sumatra, 3-4 Java, 5 Bali and Nusa Tenggara, 6 Kalimantan, 7 Sulawesi, 8 Maluku, and 9 Papua. The second digit follows the province creation order.
     *
     * @return self
     */
    public function setProvinceCode($province_code)
    {
        if (is_null($province_code)) {
            array_push($this->openAPINullablesSetToNull, 'province_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('province_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['province_code'] = $province_code;

        return $this;
    }

    /**
     * Gets regency_or_city_code
     *
     * @return string|null
     */
    public function getRegencyOrCityCode()
    {
        return $this->container['regency_or_city_code'];
    }

    /**
     * Sets regency_or_city_code
     *
     * @param string|null $regency_or_city_code Four-digit Indonesian government administrative region code for the regency or city, extracted from digits 1-4 of the submitted NIK number.              Source system: Kode Wilayah Administrasi Pemerintahan, maintained by Indonesia's Ministry of Home Affairs. Format: two-digit province code followed by a two-digit regency or city sequence; suffixes 01-69 identify regencies and suffixes 71-99 identify cities. The NIK stores this value without dot separators.
     *
     * @return self
     */
    public function setRegencyOrCityCode($regency_or_city_code)
    {
        if (is_null($regency_or_city_code)) {
            array_push($this->openAPINullablesSetToNull, 'regency_or_city_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('regency_or_city_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['regency_or_city_code'] = $regency_or_city_code;

        return $this;
    }

    /**
     * Gets district_code
     *
     * @return string|null
     */
    public function getDistrictCode()
    {
        return $this->container['district_code'];
    }

    /**
     * Sets district_code
     *
     * @param string|null $district_code Six-digit Indonesian government administrative region code for the district (kecamatan), extracted from digits 1-6 of the submitted NIK number.              Source system: Kode Wilayah Administrasi Pemerintahan, maintained by Indonesia's Ministry of Home Affairs. Format: two-digit province code, two-digit regency or city code, and two-digit district sequence. The NIK stores this value without dot separators.
     *
     * @return self
     */
    public function setDistrictCode($district_code)
    {
        if (is_null($district_code)) {
            array_push($this->openAPINullablesSetToNull, 'district_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('district_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['district_code'] = $district_code;

        return $this;
    }

    /**
     * Gets sex_national_id_number
     *
     * @return string|null
     */
    public function getSexNationalIdNumber()
    {
        return $this->container['sex_national_id_number'];
    }

    /**
     * Sets sex_national_id_number
     *
     * @param string|null $sex_national_id_number Sex extracted from the birth-day portion of the submitted NIK number.              Known values: - Male: The encoded day value is 40 or lower. - Female: The encoded day value is greater than 40.
     *
     * @return self
     */
    public function setSexNationalIdNumber($sex_national_id_number)
    {
        if (is_null($sex_national_id_number)) {
            array_push($this->openAPINullablesSetToNull, 'sex_national_id_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sex_national_id_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sex_national_id_number'] = $sex_national_id_number;

        return $this;
    }

    /**
     * Gets serial_number
     *
     * @return string|null
     */
    public function getSerialNumber()
    {
        return $this->container['serial_number'];
    }

    /**
     * Sets serial_number
     *
     * @param string|null $serial_number Four-digit issuance serial number extracted from digits 13-16 of the submitted NIK number.
     *
     * @return self
     */
    public function setSerialNumber($serial_number)
    {
        if (is_null($serial_number)) {
            array_push($this->openAPINullablesSetToNull, 'serial_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('serial_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['serial_number'] = $serial_number;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return string|null
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param string|null $phone_number The phone number submitted for this verification, if provided.              Format: international E.164 phone number.
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            array_push($this->openAPINullablesSetToNull, 'phone_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('phone_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets consent_given_at
     *
     * @return \DateTime|null
     */
    public function getConsentGivenAt()
    {
        return $this->container['consent_given_at'];
    }

    /**
     * Sets consent_given_at
     *
     * @param \DateTime|null $consent_given_at The consent timestamp submitted for this verification.
     *
     * @return self
     */
    public function setConsentGivenAt($consent_given_at)
    {
        if (is_null($consent_given_at)) {
            array_push($this->openAPINullablesSetToNull, 'consent_given_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('consent_given_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['consent_given_at'] = $consent_given_at;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email The email address submitted for this verification, if provided.
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            array_push($this->openAPINullablesSetToNull, 'email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email'] = $email;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


