<?php
/**
 * MoldovaIdentityCardCredential
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Trinsic\Api\Model;

use \ArrayAccess;
use \Trinsic\Api\ObjectSerializer;

/**
 * MoldovaIdentityCardCredential Class Doc Comment
 *
 * @category Class
 * @description A Moldovan Identity Card credential, with document type &#x60;md.gov.wallet.pid.1&#x60;, retrieved from the Moldovan EVO wallet.              This credential is derived from the individual&#39;s Moldovan National Identity Card.
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MoldovaIdentityCardCredential implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MoldovaIdentityCardCredential';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'idnp' => 'string',
        'given_name' => 'string',
        'family_name' => 'string',
        'sex' => 'int',
        'nationality' => 'string',
        'date_of_birth' => '\DateTime',
        'age_over18' => 'bool',
        'age_over21' => 'bool',
        'resident_address' => 'string',
        'resident_country' => 'string',
        'resident_region' => 'string',
        'resident_city' => 'string',
        'resident_street' => 'string',
        'resident_house_number' => 'string',
        'resident_block' => 'string',
        'resident_flat' => 'string',
        'issue_date' => '\DateTime',
        'expiry_date' => '\DateTime',
        'issuing_authority' => 'string',
        'document_type' => 'string',
        'document_series' => 'string',
        'document_number' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'idnp' => null,
        'given_name' => null,
        'family_name' => null,
        'sex' => 'int32',
        'nationality' => null,
        'date_of_birth' => 'date',
        'age_over18' => null,
        'age_over21' => null,
        'resident_address' => null,
        'resident_country' => null,
        'resident_region' => null,
        'resident_city' => null,
        'resident_street' => null,
        'resident_house_number' => null,
        'resident_block' => null,
        'resident_flat' => null,
        'issue_date' => 'date',
        'expiry_date' => 'date',
        'issuing_authority' => null,
        'document_type' => null,
        'document_series' => null,
        'document_number' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'idnp' => true,
        'given_name' => true,
        'family_name' => true,
        'sex' => true,
        'nationality' => true,
        'date_of_birth' => true,
        'age_over18' => true,
        'age_over21' => true,
        'resident_address' => true,
        'resident_country' => true,
        'resident_region' => true,
        'resident_city' => true,
        'resident_street' => true,
        'resident_house_number' => true,
        'resident_block' => true,
        'resident_flat' => true,
        'issue_date' => true,
        'expiry_date' => true,
        'issuing_authority' => true,
        'document_type' => true,
        'document_series' => true,
        'document_number' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'idnp' => 'idnp',
        'given_name' => 'givenName',
        'family_name' => 'familyName',
        'sex' => 'sex',
        'nationality' => 'nationality',
        'date_of_birth' => 'dateOfBirth',
        'age_over18' => 'ageOver18',
        'age_over21' => 'ageOver21',
        'resident_address' => 'residentAddress',
        'resident_country' => 'residentCountry',
        'resident_region' => 'residentRegion',
        'resident_city' => 'residentCity',
        'resident_street' => 'residentStreet',
        'resident_house_number' => 'residentHouseNumber',
        'resident_block' => 'residentBlock',
        'resident_flat' => 'residentFlat',
        'issue_date' => 'issueDate',
        'expiry_date' => 'expiryDate',
        'issuing_authority' => 'issuingAuthority',
        'document_type' => 'documentType',
        'document_series' => 'documentSeries',
        'document_number' => 'documentNumber'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'idnp' => 'setIdnp',
        'given_name' => 'setGivenName',
        'family_name' => 'setFamilyName',
        'sex' => 'setSex',
        'nationality' => 'setNationality',
        'date_of_birth' => 'setDateOfBirth',
        'age_over18' => 'setAgeOver18',
        'age_over21' => 'setAgeOver21',
        'resident_address' => 'setResidentAddress',
        'resident_country' => 'setResidentCountry',
        'resident_region' => 'setResidentRegion',
        'resident_city' => 'setResidentCity',
        'resident_street' => 'setResidentStreet',
        'resident_house_number' => 'setResidentHouseNumber',
        'resident_block' => 'setResidentBlock',
        'resident_flat' => 'setResidentFlat',
        'issue_date' => 'setIssueDate',
        'expiry_date' => 'setExpiryDate',
        'issuing_authority' => 'setIssuingAuthority',
        'document_type' => 'setDocumentType',
        'document_series' => 'setDocumentSeries',
        'document_number' => 'setDocumentNumber'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'idnp' => 'getIdnp',
        'given_name' => 'getGivenName',
        'family_name' => 'getFamilyName',
        'sex' => 'getSex',
        'nationality' => 'getNationality',
        'date_of_birth' => 'getDateOfBirth',
        'age_over18' => 'getAgeOver18',
        'age_over21' => 'getAgeOver21',
        'resident_address' => 'getResidentAddress',
        'resident_country' => 'getResidentCountry',
        'resident_region' => 'getResidentRegion',
        'resident_city' => 'getResidentCity',
        'resident_street' => 'getResidentStreet',
        'resident_house_number' => 'getResidentHouseNumber',
        'resident_block' => 'getResidentBlock',
        'resident_flat' => 'getResidentFlat',
        'issue_date' => 'getIssueDate',
        'expiry_date' => 'getExpiryDate',
        'issuing_authority' => 'getIssuingAuthority',
        'document_type' => 'getDocumentType',
        'document_series' => 'getDocumentSeries',
        'document_number' => 'getDocumentNumber'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('idnp', $data ?? [], null);
        $this->setIfExists('given_name', $data ?? [], null);
        $this->setIfExists('family_name', $data ?? [], null);
        $this->setIfExists('sex', $data ?? [], null);
        $this->setIfExists('nationality', $data ?? [], null);
        $this->setIfExists('date_of_birth', $data ?? [], null);
        $this->setIfExists('age_over18', $data ?? [], null);
        $this->setIfExists('age_over21', $data ?? [], null);
        $this->setIfExists('resident_address', $data ?? [], null);
        $this->setIfExists('resident_country', $data ?? [], null);
        $this->setIfExists('resident_region', $data ?? [], null);
        $this->setIfExists('resident_city', $data ?? [], null);
        $this->setIfExists('resident_street', $data ?? [], null);
        $this->setIfExists('resident_house_number', $data ?? [], null);
        $this->setIfExists('resident_block', $data ?? [], null);
        $this->setIfExists('resident_flat', $data ?? [], null);
        $this->setIfExists('issue_date', $data ?? [], null);
        $this->setIfExists('expiry_date', $data ?? [], null);
        $this->setIfExists('issuing_authority', $data ?? [], null);
        $this->setIfExists('document_type', $data ?? [], null);
        $this->setIfExists('document_series', $data ?? [], null);
        $this->setIfExists('document_number', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets idnp
     *
     * @return string|null
     */
    public function getIdnp()
    {
        return $this->container['idnp'];
    }

    /**
     * Sets idnp
     *
     * @param string|null $idnp The individual's IDNP (Numărul de Identificare Personal), the Moldovan state personal identification number.              This is a 13-digit number which uniquely identifies all natural persons in the Republic of Moldova. It has the format `2YYYOOOSSSSSX`, where: - `2` is the literal number `2` to indicate that the identifier belongs to a natural person - `YYY` is the last 3 digits of the year in which the identifier was issued - `OOO` is the code of the registrar office which issued the identifier - `SSSSS` is the sequential birth number for that year - `X` is a check digit              Note that the year encoded in the identifier is not necessarily the same as the year of birth of the individual.
     *
     * @return self
     */
    public function setIdnp($idnp)
    {
        if (is_null($idnp)) {
            array_push($this->openAPINullablesSetToNull, 'idnp');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('idnp', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['idnp'] = $idnp;

        return $this;
    }

    /**
     * Gets given_name
     *
     * @return string|null
     */
    public function getGivenName()
    {
        return $this->container['given_name'];
    }

    /**
     * Sets given_name
     *
     * @param string|null $given_name The individual's given name(s), as recorded on their Moldovan identity card.
     *
     * @return self
     */
    public function setGivenName($given_name)
    {
        if (is_null($given_name)) {
            array_push($this->openAPINullablesSetToNull, 'given_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('given_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['given_name'] = $given_name;

        return $this;
    }

    /**
     * Gets family_name
     *
     * @return string|null
     */
    public function getFamilyName()
    {
        return $this->container['family_name'];
    }

    /**
     * Sets family_name
     *
     * @param string|null $family_name The individual's family name (surname), as recorded on their Moldovan identity card.
     *
     * @return self
     */
    public function setFamilyName($family_name)
    {
        if (is_null($family_name)) {
            array_push($this->openAPINullablesSetToNull, 'family_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('family_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['family_name'] = $family_name;

        return $this;
    }

    /**
     * Gets sex
     *
     * @return int|null
     */
    public function getSex()
    {
        return $this->container['sex'];
    }

    /**
     * Sets sex
     *
     * @param int|null $sex The individual's sex, as an ISO/IEC 5218 numeric code.              Possible values: - 0: Not known - 1: Male - 2: Female - 9: Not applicable
     *
     * @return self
     */
    public function setSex($sex)
    {
        if (is_null($sex)) {
            array_push($this->openAPINullablesSetToNull, 'sex');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sex', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sex'] = $sex;

        return $this;
    }

    /**
     * Gets nationality
     *
     * @return string|null
     */
    public function getNationality()
    {
        return $this->container['nationality'];
    }

    /**
     * Sets nationality
     *
     * @param string|null $nationality The individual's nationality, as an ISO 3166-1 alpha-2 country code.              Moldovan nationals are `MD`.
     *
     * @return self
     */
    public function setNationality($nationality)
    {
        if (is_null($nationality)) {
            array_push($this->openAPINullablesSetToNull, 'nationality');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('nationality', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['nationality'] = $nationality;

        return $this;
    }

    /**
     * Gets date_of_birth
     *
     * @return \DateTime|null
     */
    public function getDateOfBirth()
    {
        return $this->container['date_of_birth'];
    }

    /**
     * Sets date_of_birth
     *
     * @param \DateTime|null $date_of_birth The date of birth of the individual.
     *
     * @return self
     */
    public function setDateOfBirth($date_of_birth)
    {
        if (is_null($date_of_birth)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_birth');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_birth', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_birth'] = $date_of_birth;

        return $this;
    }

    /**
     * Gets age_over18
     *
     * @return bool|null
     */
    public function getAgeOver18()
    {
        return $this->container['age_over18'];
    }

    /**
     * Sets age_over18
     *
     * @param bool|null $age_over18 Whether the individual is at least 18 years of age at the time of issuance of the digital credential.
     *
     * @return self
     */
    public function setAgeOver18($age_over18)
    {
        if (is_null($age_over18)) {
            array_push($this->openAPINullablesSetToNull, 'age_over18');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('age_over18', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['age_over18'] = $age_over18;

        return $this;
    }

    /**
     * Gets age_over21
     *
     * @return bool|null
     */
    public function getAgeOver21()
    {
        return $this->container['age_over21'];
    }

    /**
     * Sets age_over21
     *
     * @param bool|null $age_over21 Whether the individual is at least 21 years of age at the time of issuance of the digital credential.
     *
     * @return self
     */
    public function setAgeOver21($age_over21)
    {
        if (is_null($age_over21)) {
            array_push($this->openAPINullablesSetToNull, 'age_over21');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('age_over21', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['age_over21'] = $age_over21;

        return $this;
    }

    /**
     * Gets resident_address
     *
     * @return string|null
     */
    public function getResidentAddress()
    {
        return $this->container['resident_address'];
    }

    /**
     * Sets resident_address
     *
     * @param string|null $resident_address The individual's full registered residential address as a single formatted string.
     *
     * @return self
     */
    public function setResidentAddress($resident_address)
    {
        if (is_null($resident_address)) {
            array_push($this->openAPINullablesSetToNull, 'resident_address');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_address', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_address'] = $resident_address;

        return $this;
    }

    /**
     * Gets resident_country
     *
     * @return string|null
     */
    public function getResidentCountry()
    {
        return $this->container['resident_country'];
    }

    /**
     * Sets resident_country
     *
     * @param string|null $resident_country The country of the individual's registered residence, as an ISO 3166-1 alpha-2 country code.
     *
     * @return self
     */
    public function setResidentCountry($resident_country)
    {
        if (is_null($resident_country)) {
            array_push($this->openAPINullablesSetToNull, 'resident_country');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_country', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_country'] = $resident_country;

        return $this;
    }

    /**
     * Gets resident_region
     *
     * @return string|null
     */
    public function getResidentRegion()
    {
        return $this->container['resident_region'];
    }

    /**
     * Sets resident_region
     *
     * @param string|null $resident_region The region of the individual's registered residence.
     *
     * @return self
     */
    public function setResidentRegion($resident_region)
    {
        if (is_null($resident_region)) {
            array_push($this->openAPINullablesSetToNull, 'resident_region');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_region', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_region'] = $resident_region;

        return $this;
    }

    /**
     * Gets resident_city
     *
     * @return string|null
     */
    public function getResidentCity()
    {
        return $this->container['resident_city'];
    }

    /**
     * Sets resident_city
     *
     * @param string|null $resident_city The locality (municipality, city, town, or village) of the individual's registered residence.
     *
     * @return self
     */
    public function setResidentCity($resident_city)
    {
        if (is_null($resident_city)) {
            array_push($this->openAPINullablesSetToNull, 'resident_city');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_city', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_city'] = $resident_city;

        return $this;
    }

    /**
     * Gets resident_street
     *
     * @return string|null
     */
    public function getResidentStreet()
    {
        return $this->container['resident_street'];
    }

    /**
     * Sets resident_street
     *
     * @param string|null $resident_street The street name of the individual's registered residence.
     *
     * @return self
     */
    public function setResidentStreet($resident_street)
    {
        if (is_null($resident_street)) {
            array_push($this->openAPINullablesSetToNull, 'resident_street');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_street', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_street'] = $resident_street;

        return $this;
    }

    /**
     * Gets resident_house_number
     *
     * @return string|null
     */
    public function getResidentHouseNumber()
    {
        return $this->container['resident_house_number'];
    }

    /**
     * Sets resident_house_number
     *
     * @param string|null $resident_house_number The house or building number of the individual's registered residence.
     *
     * @return self
     */
    public function setResidentHouseNumber($resident_house_number)
    {
        if (is_null($resident_house_number)) {
            array_push($this->openAPINullablesSetToNull, 'resident_house_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_house_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_house_number'] = $resident_house_number;

        return $this;
    }

    /**
     * Gets resident_block
     *
     * @return string|null
     */
    public function getResidentBlock()
    {
        return $this->container['resident_block'];
    }

    /**
     * Sets resident_block
     *
     * @param string|null $resident_block The building block (bloc) of the individual's registered residence, where applicable.
     *
     * @return self
     */
    public function setResidentBlock($resident_block)
    {
        if (is_null($resident_block)) {
            array_push($this->openAPINullablesSetToNull, 'resident_block');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_block', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_block'] = $resident_block;

        return $this;
    }

    /**
     * Gets resident_flat
     *
     * @return string|null
     */
    public function getResidentFlat()
    {
        return $this->container['resident_flat'];
    }

    /**
     * Sets resident_flat
     *
     * @param string|null $resident_flat The flat (apartment) number of the individual's registered residence, where applicable.
     *
     * @return self
     */
    public function setResidentFlat($resident_flat)
    {
        if (is_null($resident_flat)) {
            array_push($this->openAPINullablesSetToNull, 'resident_flat');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resident_flat', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['resident_flat'] = $resident_flat;

        return $this;
    }

    /**
     * Gets issue_date
     *
     * @return \DateTime|null
     */
    public function getIssueDate()
    {
        return $this->container['issue_date'];
    }

    /**
     * Sets issue_date
     *
     * @param \DateTime|null $issue_date The date the physical identity card, used to create this digital credential, was issued.
     *
     * @return self
     */
    public function setIssueDate($issue_date)
    {
        if (is_null($issue_date)) {
            array_push($this->openAPINullablesSetToNull, 'issue_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issue_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issue_date'] = $issue_date;

        return $this;
    }

    /**
     * Gets expiry_date
     *
     * @return \DateTime|null
     */
    public function getExpiryDate()
    {
        return $this->container['expiry_date'];
    }

    /**
     * Sets expiry_date
     *
     * @param \DateTime|null $expiry_date The date the physical identity card, used to create this digital credential, expires.
     *
     * @return self
     */
    public function setExpiryDate($expiry_date)
    {
        if (is_null($expiry_date)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expiry_date'] = $expiry_date;

        return $this;
    }

    /**
     * Gets issuing_authority
     *
     * @return string|null
     */
    public function getIssuingAuthority()
    {
        return $this->container['issuing_authority'];
    }

    /**
     * Sets issuing_authority
     *
     * @param string|null $issuing_authority The name of the authority that issued the identity card.
     *
     * @return self
     */
    public function setIssuingAuthority($issuing_authority)
    {
        if (is_null($issuing_authority)) {
            array_push($this->openAPINullablesSetToNull, 'issuing_authority');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('issuing_authority', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['issuing_authority'] = $issuing_authority;

        return $this;
    }

    /**
     * Gets document_type
     *
     * @return string|null
     */
    public function getDocumentType()
    {
        return $this->container['document_type'];
    }

    /**
     * Sets document_type
     *
     * @param string|null $document_type The document type              TODO: Get example values
     *
     * @return self
     */
    public function setDocumentType($document_type)
    {
        if (is_null($document_type)) {
            array_push($this->openAPINullablesSetToNull, 'document_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_type'] = $document_type;

        return $this;
    }

    /**
     * Gets document_series
     *
     * @return string|null
     */
    public function getDocumentSeries()
    {
        return $this->container['document_series'];
    }

    /**
     * Sets document_series
     *
     * @param string|null $document_series The series of the underlying physical identity card.              This is the prefix to the full Moldovan identity card number, which is in the format `SNNN...`, where:              - `S` is a one-letter document series - `NNN...` is a document number (typically 8 digits)
     *
     * @return self
     */
    public function setDocumentSeries($document_series)
    {
        if (is_null($document_series)) {
            array_push($this->openAPINullablesSetToNull, 'document_series');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_series', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_series'] = $document_series;

        return $this;
    }

    /**
     * Gets document_number
     *
     * @return string|null
     */
    public function getDocumentNumber()
    {
        return $this->container['document_number'];
    }

    /**
     * Sets document_number
     *
     * @param string|null $document_number The number of the underlying physical identity card, excluding the series.              This is the suffix to the full Moldovan identity card number, which is in the format `SNNN...`, where:              - `S` is a one-letter document series - `NNN...` is a document number (typically 8 digits)
     *
     * @return self
     */
    public function setDocumentNumber($document_number)
    {
        if (is_null($document_number)) {
            array_push($this->openAPINullablesSetToNull, 'document_number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('document_number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['document_number'] = $document_number;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


