<?php
/**
 * Iso180135AamvaDomesticDrivingPrivilegeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Trinsic\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trinsic API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Trinsic\Api\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * Iso180135AamvaDomesticDrivingPrivilegeTest Class Doc Comment
 *
 * @category    Class
 * @description A single domestic driving privilege from the AAMVA &#x60;domestic_driving_privileges&#x60; field, per AAMVA Section 7.2.4.
 * @package     Trinsic\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class Iso180135AamvaDomesticDrivingPrivilegeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Iso180135AamvaDomesticDrivingPrivilege"
     */
    public function testIso180135AamvaDomesticDrivingPrivilege()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vehicle_class"
     */
    public function testPropertyVehicleClass()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vehicle_restrictions"
     */
    public function testPropertyVehicleRestrictions()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vehicle_endorsements"
     */
    public function testPropertyVehicleEndorsements()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
